[[tocK_02]]
=== 都市計画決定情報の記述とLOD


[[tocK_02_01]]
==== 都市計画決定情報モデル

都市計画決定情報とは、都市計画図書（計画図及び計画書）に含まれる情報である。都市計画決定情報は、i-URに定義された地物型を使用して記述する。CityGMLには、都市計画区域や用途地域のような目には見えない制約や制限のような概念的な地物は定義されていないため、i-URではCityGMLを拡張し新たに定義している。

標準製品仕様書で対象とする都市計画決定情報のLODは、LOD1とする。このとき、LODには外部・内部の区別はない。


[requirement]
.都市計画決定情報のLOD条件
====
[%metadata]
identifier:: /req/urf/1
subject:: 妥当な都市計画決定情報データセットの要件
description:: 都市計画決定情報に適用されるLODは、LOD1とする。
====


[[tocK_02_02]]
==== 使用可能な地物型とLOD

都市計画決定情報は、i-URのUrbanFunctionモジュールに定義されたurf:UrbanFunctionAreaの下位型を用いて記述する。urf:UrbanFunctionAreaを継承するurf:Zoneは、概念的な区域であり、これをさらに継承して、都市計画区域や用途地域、地区計画のような地物型が、都市計画決定情報として都市計画法及び関連法令に基づき定義されている。

// 都市計画決定情報モデルの記述に使用する地物型と空間属性
[[tab-K-1]]
include::../../../common/sections/com_URF_SpatialAttribute.adoc[]


[requirement]
.都市計画の区域記述条件
====
[%metadata]
identifier:: /req/urf/2
subject:: 妥当な都市計画決定情報データセットの要件
description:: 都市計画の区域は、urf:Zoneを継承する地物型を用いて記述する。
====

urf:Zoneは具象の地物型であり、これを使用して都市オブジェクトを作成できるが、都市計画決定情報は、urf:Zoneを継承する地物型（例：urf:UrbanPlanningArea）を使用して記述しなければならない。 +
なお、都市計画の区域以外に法令で定める区域（例：港湾区域）は、urf:Zoneを使用して記述する（<<tocU>>参照）。


[[tocK_02_03]]
==== 都市計画決定情報のLOD定義

都市計画決定情報モデルは、LOD1のみを対象とする。 +
都市計画決定情報モデル（LOD1）では、都市計画の区域の形状を、高さをもたない面として表現する。

// 都市計画決定情報モデル（LOD1）の取得イメージ
[[tab-K-2]]
include::../../../common/sections/com_URF_Acquire_lod1.adoc[]

