[[tocU_05]]
=== 標準的な作業手順

// TBD

幾何オブジェクトを作成する際の標準的な作業手順及び作業上の留意事項を示す。

[[tocU_05_01]]
==== 幾何オブジェクトの作成



区域モデルの作成に必要となる原典資料を以下に示す。

[[tab-U-4]]
[cols="1a,3a,3a,3a"]
.原典資料一覧
|===
| | 区域の境界に囲まれた面 | 高さ | 主題属性

|  LOD1
| 以下のいずれかのデータを一つ以上使用する。

* GISデータ
* 法定図書
| ―
| 以下のいずれかのデータを一つ以上使用する。

* GISデータ
* 法定図書

|===


[[tocU_05_01_01]]
===== LOD1

GISデータが存在する場合には、これを利用する。ただし、利用可能なGISデータは位置正確度をもつもののみとする。GISデータを利用する場合は、原典資料リストにその地図情報レベルを記載すること。

GISデータが無い場合には、法定図書に含まれる図面を使用し、既成図数値化により幾何オブジェクトを作成する。既成図数値化の作業手順及び精度管理は、「作業規程の準則　第3編第5章　既成図数値化」に従う。


[[tocU_05_02]]
==== 主題属性の作成

GISデータが存在する場合には、これを利用する。また、GISデータの属性に不足がある場合には、法定図書を原典資料とする。



[[tocU_05_03]]
==== 作業上の留意事項



[requirement]
.現況との差異への対応
====
[%metadata]
identifier:: /att/area/1
subject:: 妥当な区域データセットの要件
class:: 留意事項
[statement]
--
法定図書の図面から区域の境界を入力する場合、図面の作成時点が古い等の理由により、現況の背景地形とずれる可能性がある。背景地形とのずれへの対応として以下の2つの方法がある。

. 現況の背景地形に合わせて、背景地図上で境界を入力する。
. 図面上に記載された線をデジタイズし、境界を入力する。

a）の方法は、区域の境界が、「河川の中心線」、「道路の中心線」、「行政界」というように、地物の形状を用いて指定されている場合に有効である。b）の方法は、地物との相対的な位置関係ではなく、図面上の境界の位置が「正」となる場合に有効である。 +
いずれの方法が適切であるかは、区域の指定方法や図面の位置づけにより異なるため、区域の管理者やデータ整備主体への確認が必要である。
--
====


[requirement]
.法定図書からの主題属性入力
====
[%metadata]
identifier:: /att/area/2
subject:: 妥当な区域データセットの要件
class:: 留意事項
[statement]
--
区域に付与すべき属性は、法定図書で網羅される。しかしながら、法定図書の多くは紙資料として管理されており、資料の収集やデータの入力に労力を要する。また、文章や図表として法定図書に記載されており、GISデータとしてデータ化することが困難な情報も含まれる。そのため、主題属性の入力対象は、これにかかる作業量も考慮し、決定する必要がある。
--
====



