[[tocU_02]]
=== 区域モデルの記述とLOD

[[tocU_02_01]]
==== 区域モデル

区域とは、特定の明確な目的からひとまとまりに区分けされた空間範囲をさし、その空間範囲内の共通的性格を前提とした均質的な一定の規制が設定される。標準製品仕様書では、法令により定められた区域を対象とする。

区域は、i-URに定義された地物型を使用して記述する。CityGMLには、目には見えない制約や制限のような概念的な地物は定義されていないため、i-URではCityGMLを拡張し新たに定義している。

標準製品仕様書で対象とする区域モデルのLODは、LOD1とする。このとき、LODには外部・内部の区別はない。


[[tocU_02_02]]
==== 使用可能な地物型とLOD

i-URには、区域を記述するための地物型が用意されている。詳細度（LOD）ごとに、使用すべき地物型やその空間属性が異なる。


[requirement]
.区域記述のLOD対応条件
====
[%metadata]
identifier:: /req/area/1
subject:: 妥当な区域データセットの要件
description:: 区域の記述には、指定されたLODに対応する地物型及び空間属性を使用する。
====

区域は、i-URのUrbanFunctionモジュールに定義されたurf:Zoneを用いて記述する。urf:Zoneは法令で定められた区域に該当する。 +
標準製品仕様書が対象とする区域モデルのLODはLOD1のみである。使用する地物型とLODを<<tab-U-1>>に示す。

// 区域モデルの記述に使用する地物型と空間属性
[[tab-U-1]]
include::../../../common/sections/com_area_SpatialAttribute.adoc[]


[[tocU_02_03]]
==== 区域モデルのLOD定義

[[tocU_02_03_01]]
===== LOD1

区域モデル（LOD1）の定義を<<tab-U-2>>に示す。

[[tab-U-2]]
.区域モデル（LOD1）の定義
include::../../../common/sections/com_area_Definition_lod10.adoc[]


// 区域モデル（LOD1）の取得イメージ
[[tab-U-3]]
include::../../../common/sections/com_area_Acquire_lod1.adoc[]

