[[tocU_03]]
=== urf:Zone

urf:Zoneは、法令等により定められた区域の記述に使用する型である。 +
なお、都市計画法により定められた区域は、都市計画決定情報モデルにより記述する。


[[tocU_03_01]]
==== urf:Zoneの空間属性

urf:Zoneの空間属性は、LOD1のみである。


[[tocU_03_01_01]]
===== LOD1

urf:Zoneの空間属性は、LOD1において、高さをもたない多曲面（urf:lod1MultiSurface）として表現する。


[requirement]
.urf:lod1MultiSurfaceの面定義
====
[%metadata]
identifier:: /req/area/2
subject:: 妥当な区域データセットの要件
description:: urf:lod1MultiSurfaceで示される面は、区域の境界により囲まれた、高さをもたない多曲面とする。
====

なお、区域の境界をurf:Boundaryを用いて地物として記述することができる。


[[tocU_03_02]]
==== 区域の主題属性


[[tocU_03_02_01]]
===== urf:function

urf:Zoneは、法令により定められた区域を定義する汎用的な地物型であり、属性urf:functionによりその区域の種類を識別する。


[requirement]
.urf:Zoneの識別方法
====
[%metadata]
identifier:: /req/area/3
subject:: 妥当な区域データセットの要件
description:: urf:Zoneの種類は、属性urf:functionにより識別できなければならない。
====

標準製品仕様書では、属性urf:functionの定義域として、港湾区域や河川区域等が用意されているが、この定義域が不足する場合には、定義域に必要な区域の名称を追加できる。定義域を追加する場合は、拡張製品仕様書においてurf:Zoneの定義に追加したい区域の名称を追記するとともに、urf:functionが参照するコードリストZone_function.xmlにコードとコードに対応する説明を追加する。

ただし、都市計画の区域のように、urf:Zoneを継承し、地物型が定義されている場合には、urf:Zoneではなく、これを継承するそれぞれの地物型を使用して記述しなければならない。


[requirement]
.urf:Zoneの継承地物型使用条件
====
[%metadata]
identifier:: /req/area/4
subject:: 妥当な区域データセットの要件
description:: urf:Zoneを継承する地物型が存在する場合には、urf:Zoneを継承した地物型を使用して記述しなければならない。
====


[[tocU_03_02_02]]
===== ADEで拡張された属性の記述

// 付属書U内にデータ品質属性の記載なしのためリンク張れない。

CityGML3.0では、地物型ごとに、属性を拡張するためのデータ型ADEOfXXX（XXXには地物型の名称が入る）が用意されている。また、拡張したデータ型を地物の属性として記述するための主題属性adeOfXXX（XXXには地物型の名称が入る）も用意されている。例えば、建築物（Building）という地物型に属性を追加したい場合、ADEOfBuildingを使う。このデータ型を継承して新しい属性を定義することで、主題属性adeOfBuildingの型として記述できるようになる。

ここで、区域のデータ品質属性は、上述の仕組みを使って拡張して定義されたデータ型である。これらのデータ型を記述する場合には、拡張した地物型に対応する主題属性adeOfXXX（XXXには地物型の名称が入る）の型として記述しなければならない。

例えば、データ品質属性はADEOfAbstractCityObjectを継承して定義されているため、adeOfAbstractCityObjectの型として記述する。

このように、ADEで拡張された属性が、どの地物型を拡張して定義されているかによって、主題属性として値を記述する場所が異なることに注意が必要である。

