[[tocR_03]]
=== veg:AbstractVegetationObject

veg:AbstractVegetationObjectは植生の記述に使用する抽象地物型である。 +
実装においては、この下位型の具象となる以下の地物型を使用する。

* veg:SolitaryVegetationObjectは、単独の樹木（単独木）の記述に使用する地物型である。
* veg:PlantCoverは、植被の記述に使用する地物型である。この地物型は、歩道上の植栽など、個々の樹木を識別せず、まとめて記述する場合に使用する。


[[tocR_03_01]]
==== 植生の空間属性


[[tocR_03_01_01]]
===== LOD0

veg:SolitaryVegetationObjectの空間属性は、LOD0において、面（core:lod0MultiSurface）により表現する。 +
このとき、植生オブジェクトは、植生モデル（LOD0）の定義に従ったものでなければならない。


[requirement]
.植生オブジェクトのLOD0形状定義
====
[%metadata]
identifier:: /req/veg/2
subject:: 妥当な植生データセットの要件
description:: 植生オブジェクトのLOD0の形状は、植生モデル（LOD0）の定義に従う。
====

なお、「<<gsi_ops,作業規程の準則 付録７ 公共測量標準図式>>」（以下、「公共測量標準図式」という）に基づく表現を行う場合には、数値地形図属性（urc:DmAttribute）を使用する。


[[tocR_03_01_02]]
===== LOD1

veg:SolitaryVegetationObjectの空間属性は、LOD1において、立体により表現する。 +
このとき、植生オブジェクトは、植生モデル（LOD1）の定義に従ったものでなければならない。


[requirement]
.植生オブジェクトのLOD1形状定義
====
[%metadata]
identifier:: /req/veg/3
subject:: 妥当な植生データセットの要件
description:: 植生オブジェクトのLOD1の形状は、植生モデル（LOD1）の定義に従う。
====

植生モデル（LOD1）では、植生の上方からの正射影の外周を、一律の高さで上向きに押し出した立体として表現する。


[[tocR_03_01_03]]
===== LOD2

veg:SolitaryVegetationObjectの空間属性は、LOD2において、立体又は多曲面で表現する。 +
このとき、植生オブジェクトは、植生モデル（LOD2）の定義に従ったものでなければならない。


[requirement]
.植生オブジェクトのLOD2形状定義
====
[%metadata]
identifier:: /req/veg/4
subject:: 妥当な植生データセットの要件
description:: 植生オブジェクトのLOD2の形状は、植生モデル（LOD2）の定義に従う。
====

植生モデル（LOD2）では、形状の再現度の異なるLOD2.0及びLOD2.1に分かれる。

* veg:SolitaryVegetationObject（単独木）の場合
** LOD2.0では、樹冠と樹幹をそれぞれ簡略化した立体を組み合わせた立体として表現する。簡略化した立体とは、楕円体、球体、円錐、角錐、角柱、円柱などの単純な立体図形をいう。
** LOD2.1では、樹冠及び樹幹の外形を構成する特徴点により作成した立体として表現する。一定高さごとに樹冠の横断面を作成し、この頂点を結び外形を構成する（樹冠内部の主枝等の表現は行わない。）が、ユースケースの必要に応じて詳細化してよい。
* veg:PlantCover（植被）の場合
** LOD2.0では、3m以上の植被は、植被の表層の高さを取得し、比高3m以上の形状を再現した立体として表現する。立体は、特徴点を結ぶ三角網から構成される面を境界面とする立体とする。3m未満の植被は、底面を最高高さまで立ち上げた立体とする。
** LOD2.1では、植被は、表層の高さを取得し、比高1m以上を再現する。外形は特徴点を結ぶ三角網から構成される面を立体として表現する。


[[tocR_03_01_04]]
===== LOD3

veg:SolitaryVegetationObjectの空間属性は、LOD3において、多曲面又は立体として表現する。 +
このとき、植生オブジェクトは、植生モデル（LOD3）の定義に従ったものでなければならない。


[requirement]
.植生オブジェクトのLOD3形状定義
====
[%metadata]
identifier:: /req/veg/5
subject:: 妥当な植生データセットの要件
description:: 植生オブジェクトのLOD3の形状は、植生モデル（LOD3）の定義に従う。
====

植生モデル（LOD3）は、植生の形状を多曲面又は立体により詳細に再現する。樹冠内部の主枝や葉を表現することもできる。 +
LOD2が測量により作成することを前提とした区分であるのに対し、LOD3は3DモデルやCADデータからの変換により作成することを前提とした区分である。


[[tocR_03_02]]
==== 植生の主題属性

植生の主題属性には、あらかじめCityGML又はGMLにおいて定義された属性（接頭辞veg、core、gml）がある。

また、標準製品仕様書では、i-URにおいて拡張された、作成したデータの品質に関する情報を格納するための属性（urc:DataQualityAttribute）や公共測量標準図式に従った表現に必要となる属性（urc:DmAttribute）を定義している。 +
さらに、特定の分野において植生を管理したい場合に、その分野における位置や識別に関する属性
（uro:FacilityIdAttribute）、施設区分に関する属性（uro:FacilityTypeAttribute）、その分野における施設管理に必要な属性（uro:FacilityAttribute）を利用することもできる。


[[tocR_03_02_01]]
===== 数値地形図属性（urc:DmAttribute）

公共測量標準図式に従った形状表現を行うために必要な属性である。LOD0の幾何オブジェクトの他、数値地形図との互換性を保つために必要な情報が、属性として定義されている。


[[tocR_03_02_02]]
===== データ品質属性（urc:DataQualityAttribute）

使用した原典資料やそれに基づくデータの品質、また、採用したLODは、データセットのメタデータに記録できる。ただし、データセット全体に対して一つのメタデータを作成することが基本となり、個々の都市オブジェクトの品質を記録することは困難である。

そこで、標準製品仕様書では、個々のデータに対してデータ品質に関する情報を記述するための属性として、「データ品質属性」（urc:DataQualityAttribute）を定義している。データ品質属性は、属性としてデータ作成に使用した原典資料の地図情報レベル、その他原典資料の諸元、精緻化したLOD等をもつ。

3D都市モデルに含まれる全ての単独木オブジェクトは、このデータ品質属性を必ず作成しなければならない。


[[tocR_03_02_03]]
===== ADEで拡張された属性の記述

CityGML3.0では、地物型ごとに、属性を拡張するためのデータ型ADEOfXXX（XXXには地物型の名称が入る）が用意されている。また、拡張したデータ型を地物の属性として記述するための主題属性adeOfXXX（XXXには地物型の名称が入る）も用意されている。例えば、建築物（Building）という地物型に属性を追加したい場合、ADEOfBuildingを使う。このデータ型を継承して新しい属性を定義することで、主題属性adeOfBuildingの型として記述できるようになる。

ここで、植生の<<tocR_03_02_02,データ品質属性>>は、上述の仕組みを使って拡張して定義されたデータ型である。これらのデータ型を記述する場合には、拡張した地物型に対応する主題属性adeOfXXX（XXXには地物型の名称が入る）の型として記述しなければならない。

例えば、<<tocR_03_02_02,データ品質属性>>はADEOfAbstractCityObjectを継承して定義されているため、adeOfAbstractCityObjectの型として記述する。

このように、ADEで拡張された属性が、どの地物型を拡張して定義されているかによって、主題属性として値を記述する場所が異なることに注意が必要である。

