[[tocJ_03]]
=== 災害リスク（浸水）

災害リスク（浸水）モデルで表現する浸水面の記述には、wtr:WaterSurfaceを使用する。


[[tocJ_03_01]]
==== 災害リスク（浸水）の空間属性

標準製品仕様書では、災害リスク（浸水）モデルのLODは、LOD1のみを対象としている。ここのとき、LODには内部・外部の区別はない。


[[tocJ_03_01_01]]
===== LOD1

災害リスク（浸水）は、LOD1において、浸水面の形状を、高さをもつ面として表現する。高さをもつ面の記述にはgml:MultiSurfaceを使用する。gml:MultiSurfaceに含まれる隣接する面はその頂点を共有し、連続的な浸水面として表現しなければならない。また、各頂点の高さは、標高に水位を加えた高さとなる。 +
浸水面の記述には、wtr:WaterSurfaceを使用する。wtr:WaterSurfaceは部品としてのみ記述可能な地物型であり、必ずwtr:WaterBodyに含まれなければならない。 +
そのため、浸水面を記述する際には、wtr:WaterBodyの子要素としてwtr:WaterSurfaceを記述する。このとき、wtr:WaterBodyの空間属性は記述しない。


[[tocJ_03_02]]
==== 災害リスク（浸水）の下位型


[[tocJ_03_02_01]]
===== 洪水浸水想定区域

洪水浸水想定区域図データ電子化ガイドラインが対象とする「洪水浸水想定区域」をいう。 +
水防法第14条第1項に定める洪水浸水想定区域のほか、これに類する河川が氾濫した場合に浸水が想定される区域を含む。


[[tocJ_03_02_02]]
===== 内水浸水想定区域

内水浸水想定区域図作成マニュアル（案）に定める「内水浸水想定区域」をいう。 +
水防法に基づく想定最大規模降雨に対する内水による浸水が想定される区域（水防法第14条の2第1項に定める「雨水出水浸水想定区域」）、地域の既往最大降雨や他地域での大規模な降雨など一定の被害が想定される降雨に対する内水による浸水が想定される区域及び計画降雨等に対する内水による浸水が想定される区域を含む。


[[tocJ_03_02_03]]
===== 高潮浸水想定

水防法第14条の3第1項に定める「高潮浸水想定区域」をいう。


[[tocJ_03_02_04]]
===== 津波浸水想定

津波防災地域づくりに関する法律第8条第1項に定める「津波浸水想定」をいう。


[[tocJ_03_02_05]]
===== ため池ハザードマップ

ため池ハザードマップ作成の手引き（案）に定める「ため池ハザードマップ」をいう。


[[tocJ_03_03]]
==== 災害リスク（浸水）の主題属性


[[tocJ_03_03_01]]
===== 名称（gml:name）

gml:nameには、浸水想定区域等の図面に示される、図面の名称を記述する。この場合、gml:nameは必須とする。


[[tocJ_03_03_02]]
===== 浸水ランク（uro:rank、uro:orgRank）

uro:rank及びuro:orgRankは、浸水深（津波浸水想定の場合は「水位」）に応じた区分である。災害リスク（浸水）オブジェクトは、uro:rank又はuro:rankOrgのいずれか一つを必ずもつ。 +
uro:rankは、標準製品仕様書に定められた区分を適用する場合に用いる。 +
市町村等が独自に設定した浸水深（津波浸水想定の場合は「水位」）に応じた区分を適用したい場合は、uro:rankOrgを使用する。uro:rankOrgを使用する場合には、浸水深（津波浸水想定の場合は「水位」）の区分を示すコードリストを作成しなければならない。


[[tocJ_03_03_03]]
===== データ品質属性（urc:DataQualityAttribute）

使用した原典資料やそれに基づくデータの品質、また、採用したLODは、データセットのメタデータに記録できる。ただし、データセット全体に対して一つのメタデータを作成することが基本となり、個々の都市オブジェクトの品質を記録することは困難である。

そこで、標準製品仕様書では、個々のデータに対してデータ品質に関する情報を記述するための属性として、「データ品質属性」（urc:DataQualityAttribute）を定義している。データ品質属性は、属性としてデータ作成に使用した原典資料の地図情報レベル、その他原典資料の諸元、精緻化したLOD等をもつ。

3D都市モデルに含まれる全ての災害リスク（浸水）オブジェクトは、このデータ品質属性を必ず作成しなければならない。


[[tocJ_03_03_04]]
===== ADEで拡張された属性の記述

CityGML3.0では、地物型ごとに、属性を拡張するためのデータ型ADEOfXXX（XXXには地物型の名称が入る）が用意されている。また、拡張したデータ型を地物の属性として記述するための主題属性adeOfXXX（XXXには地物型の名称が入る）も用意されている。例えば、建築物（Building）という地物型に属性を追加したい場合、ADEOfBuildingを使う。このデータ型を継承して新しい属性を定義することで、主題属性adeOfBuildingの型として記述できるようになる。

ここで、災害リスク（浸水）の<<tocJ_03_03_02,災害リスク属性>>や<<tocJ_03_03_03,データ品質属性>>は、上述の仕組みを使って拡張して定義されたデータ型である。これらのデータ型を記述する場合には、拡張した地物型に対応する主題属性adeOfXXX（XXXには地物型の名称が入る）の型として記述しなければならない。

例えば、<<tocJ_03_03_02,災害リスク属性>>や<<tocJ_03_03_03,データ品質属性>>は、いずれもADEOfAbstractCityObjectを継承して定義されているため、adeOfAbstractCityObjectの型として記述する。

このように、ADEで拡張された属性が、どの地物型を拡張して定義されているかによって、主題属性として値を記述する場所が異なることに注意が必要である。

