[[tocJ_02]]
=== 災害リスクの記述とLOD


[[tocJ_02_01]]
==== 災害リスクモデル

災害リスクとは、標準製品仕様書では、以下の7種類を指す。

* 洪水浸水想定区域図データ電子化ガイドラインが対象とする「洪水浸水想定区域」
* <<mlit_int_flood_guidelines,内水浸水想定区域図作成マニュアル（案）>>に定める「内水浸水想定区域」
* 水防法第14条の3第1項に定める「高潮浸水想定区域」
* 津波防災地域づくりに関する法律第8条第1項に定める「津波浸水想定」
* <<maff_reservoir_hazard_maps,ため池ハザードマップ作成の手引き（案）>>に定める「ため池ハザードマップ」
* 土砂災害警戒区域等における土砂災害防止対策の推進に関する法律第7条第1項に定める「土砂災害警戒区域」
* 土砂災害警戒区域等における土砂災害防止対策の推進に関する法律第9条第1項に定める「土砂災害特別警戒区域」

なお、「洪水浸水想定区域」は、水防法第14条第1項に定める洪水浸水想定区域のほか、中小河川洪水浸水想定区域図作成の手引きに従って作成された洪水浸水想定区域及び急流河川における浸水想定区域検討の手引きに従って作成された浸水想定区域等、水防法に基づく洪水浸水想定区域以外の河川が氾濫した場合に浸水が想定される区域を含む。

また、「内水浸水想定区域」は、水防法に基づく想定最大規模降雨に対する内水による浸水が想定される区域（水防法第14条の2第1項に定める「雨水出水浸水想定区域」）、地域の既往最大降雨や他地域での大規模な降雨など一定の被害が想定される降雨に対する内水による浸水が想定される区域及び計画降雨等に対する内水による浸水が想定される区域を含む。

標準製品仕様書では、洪水浸水想定区域、内水浸水想定区域、高潮浸水想定区域、津波浸水想定及びため池ハザードマップを「災害リスク（浸水）モデル」、土砂災害警戒区域及び土砂災害特別警戒区域を「災害リスク（土砂災害）モデル」と区分し、それぞれLOD1のみを対象とする。このとき、LODには外部・内部の区別はない。


[[tocJ_02_02]]
==== 使用可能な地物型とLOD

災害リスクモデルは、LODごとに使用すべき地物型やその空間属性を定めている。


[requirement]
.災害リスクモデル記述のLOD対応条件
====
[%metadata]
identifier:: /req/risk/1
subject:: 妥当な災害リスクオブジェクトの要件
description:: 災害リスクモデルの記述には、指定されたLODに対応する地物型及び空間属性を使用する。
====

災害リスクモデルの各LODにおいて使用可能な地物型と空間属性を、<<tab-J-1>>に示す。

// 災害リスクモデルの記述に使用する地物型と空間属性
[[tab-J-1]]
include::../../../common/sections/com_risk_SpatialAttribute.adoc[]


[[tocJ_02_03]]
==== 災害リスクモデルのLOD定義

災害リスクモデルは、LOD1のみを対象とする。 +
災害リスクモデル（LOD1）では、災害リスクの形状を、面として表現する。

// 災害リスク（浸水）モデル（LOD1）の取得イメージ
[[tab-J-2]]
include::../../../common/sections/com_risk_Acquire_lod1_flooding.adoc[]

// 災害リスク（土砂災害）モデル（LOD1）の取得イメージ
[[tab-J-3]]
include::../../../common/sections/com_risk_Acquire_lod1_landslide.adoc[]

