[[tocJ_04]]
=== 災害リスク（土砂災害）

災害リスク（土砂災害）モデルで表現する浸水面の記述には、i-URで定義されたurf:SedimentDisasterProneAreaを使用する。


[[tocJ_04_01]]
==== 災害リスク（土砂災害）の空間属性

標準製品仕様書では、災害リスク（土砂災害）モデルのLODは、LOD1のみを対象としている。このとき、LODには内部・外部の区別はない。


[[tocJ_04_01_01]]
===== LOD1

災害リスク（土砂災害）は、LOD1において、区域の形状を、高さをもたない面として表現する。高さをもたない面の記述にはgml:MultiSurfaceを使用する。このときの面の形状は、土砂災害警戒区域又は土砂災害特別警戒区域の形状と一致し、各頂点の高さは0となる。


[[tocJ_04_02]]
==== 災害リスク（土砂災害）の主題属性


[[tocJ_04_02_01]]
===== 区域の指定と解除

区域を指定した日付は、urf:validFromにより記述できる。また、区域が解除された場合は、urf:validToにより解除日を記述できる。


[[tocJ_04_02_02]]
===== データ品質属性（urc:DataQualityAttribute）

使用した原典資料やそれに基づくデータの品質、また、採用したLODは、データセットのメタデータに記録できる。ただし、データセット全体に対して一つのメタデータを作成することが基本となり、個々の都市オブジェクトの品質を記録することは困難である。

そこで、標準製品仕様書では、個々のデータに対してデータ品質に関する情報を記述するための属性として、「データ品質属性」（urc:DataQualityAttribute）を定義している。データ品質属性は、属性としてデータ作成に使用した原典資料の地図情報レベル、その他原典資料の諸元、精緻化したLOD等をもつ。

3D都市モデルに含まれる全ての災害リスク（土砂災害）オブジェクトは、このデータ品質属性を必ず作成しなければならない。


[[tocJ_04_02_03]]
===== ADEで拡張された属性の記述

CityGML3.0では、地物型ごとに、属性を拡張するためのデータ型ADEOfXXX（XXXには地物型の名称が入る）が用意されている。また、拡張したデータ型を地物の属性として記述するための主題属性adeOfXXX（XXXには地物型の名称が入る）も用意されている。例えば、建築物（Building）という地物型に属性を追加したい場合、ADEOfBuildingを使う。このデータ型を継承して新しい属性を定義することで、主題属性adeOfBuildingの型として記述できるようになる。

ここで、災害リスク（土砂災害）の<<tocJ_04_02_02,データ品質属性>>は、上述の仕組みを使って拡張して定義されたデータ型である。これらのデータ型を記述する場合には、拡張した地物型に対応する主題属性adeOfXXX（XXXには地物型の名称が入る）の型として記述しなければならない。

<<tocJ_04_02_02,データ品質属性>>は、ADEOfAbstractCityObjectを継承して定義されているため、adeOfAbstractCityObjectの型として記述する。

このように、ADEで拡張された属性が、どの地物型を拡張して定義されているかによって、主題属性として値を記述する場所が異なることに注意が必要である。

