[[doc00_04]]
[bibliography]
== 参考文献

* [[[plateau_prod_spec_4,PLATEAU Handbook #01]]],
span:organization[国土交通省　都市局]
span:title[3D都市モデル標準製品仕様書]
span:docid.PLATEAU[PLATEAU Handbook #01]
span:date[2025-03-21]
span:edition[5.1]
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/handbooks/]

* [[[plateau_002,PLATEAU Handbook #02]]],
span:organization[国土交通省　都市局]
span:title[3D都市モデル標準作業手順書]
span:docid.PLATEAU[PLATEAU Handbook #02]
span:date[2024-09-30]
span:edition[5.1]
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/handbooks/]

* [[[gsi_geospatial_dps_manual,1]]]
span:title[地理空間データ製品仕様書作成マニュアル JPGIS 2014版]
span:organization[国土交通省　国土地理院]
span:date[2020-11]
span:uri.citation[https://www.gsi.go.jp/common/000250810.pdf]

* [[[iurban_des,i-UR 4.0]]],
span:title[Data Encoding Specification of i-Urban Revitalization -Urban Planning ADE- ver.4.0]
span:organization[内閣府　地方創生推進事務局]
span:uri.citation[https://www.chisou.go.jp/tiiki/toshisaisei/itoshisaisei/iur/index.html]

* [[[ogc_12-019,OGC 12-019]]],
span:title[OpenGIS® OGC City Geography Markup Language (CityGML) Encoding Standard, Version 3.0]
span:uri.citation[https://www.ogc.org/standards/citygml]
span:language[en]

* [[[ogc_05-099r2,OGC 05-099r2]]],
span:title[OpenGIS® GML 3.1.1 simple dictionary profile, Version 1.0.0]
span:uri.citation[https://www.ogc.org/standards/gml]
span:language[en]

* [[[iso_iec_19501,ISO/IEC 19501:2005]]],
span:title[Information technology — Open Distributed Processing — Unified Modeling Language(UML) Version 1.4.2]
span:uri.citation[https://www.iso.org/standard/32620.html]
span:language[en]

* [[[rfc_4122,amend(IETF RFC 4122)]]] span:language[en]

* [[[gml_311,amend(OGC 07-036)]]] span:language[en]

* [[[citygml_20,amend(OGC 12-019)]]] span:language[en]

* [[[citygml_30,amend(OGC 20-010)]]] span:language[en]

* [[[citygml_30_encoding,amend(OGC 21-006r2)]]] span:language[en]

* [[[iso_6707-1,amend(ISO 6707-1)]]] span:language[en]

* [[[jis_e_1001,amend(JIS E 1001:2001)]]] span:language[en]

* [[[mlit_green_roads,4]]]
span:organization[国土交通省　道路局]
span:title[道路緑化技術基準]
span:uri.citation[https://www.mlit.go.jp/road/sisaku/ryokuka/index.html]

* [[[mlit_greenery_std,5]]]
span:organization[国土交通省　都市局]
span:title[公共用緑化樹木等品質寸法規格基準（案）]
span:date[2010-02]
span:uri.citation[https://www.mlit.go.jp/notice/noticedata/sgml/035/76000224/76000224.html]

* [[[nilim_street_trees,6]]]
span:title[わが国の街路樹Ⅷ],
span:organization[国土交通省　国土技術政策総合研究所]
span:date[2018-01]
span:uri.citation[http://www.nilim.go.jp/lab/bcg/siryou/tnn/tnn1050.htm]

* [[[mlit_ks_ps_a31,7]]]
span:organization[国土交通省　国土政策局]
span:title[国土数値情報（洪水浸水想定区域）製品仕様書]
span:version[2.1]
span:date[2020-03]
span:uri.citation[https://nlftp.mlit.go.jp/ksj/gml/product_spec/KS-PS-A31-v2_1.pdf]

* [[[mlit_ks_ps_a33,8]]]
span:organization[国土交通省　不動産　建設経済局]
span:title[国土数値情報（土砂災害警戒区域）製品仕様書]
span:version[2.0]
span:date[2021-03]
span:uri.citation[https://nlftp.mlit.go.jp/ksj/gml/product_spec/KS-PS-A33-v2_0.pdf]

* [[[smlit_flooding_guideline,9]]]
span:organization[国土交通省　水管理・国土保全局　河川環境課　水防企画室　下水道部　海岸室]
span:title[浸水想定区域図データ電子化ガイドライン]
span:edition[5]
span:date[2023-02]
span:uri.citation[https://www.mlit.go.jp/river/shishin_guideline/index.html]

* [[[mlit_deluge_guidelines,10]]]
span:organization[国土交通省　水管理・国土保全局　河川環境課　水防企画室],
span:organization[国土交通省　国土技術政策総合研究所　河川研究部　水害研究室]
span:title[洪水浸水想定区域図作成マニュアル]
span:edition[4]
span:date[2017-01]
span:uri.citation[https://www.mlit.go.jp/river/shishin_guideline/index.html]

* [[[mlit_tsunami_guidelines,11]]]
span:organization[国土交通省　水管理・国土保全局　海岸室],
span:organization[国土交通省　国土技術政策総合研究所　河川研究部　海岸研究室]
span:title[津波浸水想定の設定の手引き]
span:version[2.11]
span:date[2023-04]
span:uri.citation[https://www.mlit.go.jp/sogoseisaku/point/content/001621078.pdf]

* [[[mlit_tide_guidelines,12]]]
span:organization[農林水産省　農村振興局　整備部　防災課],
span:organization[農林水産省　水産庁　漁港漁場整備部　防災漁村課],
span:organization[国土交通省　水管理・国土保全局　河川環境課],
span:organization[国土交通省　水管理・国土保全局　海岸室],
span:organization[国土交通省　港湾局　海岸　防災課]
span:title[高潮浸水想定区域図作成の手引き]
span:version[2.11]
span:date[2023-04]
span:uri.citation[https://www.mlit.go.jp/river/shishin_guideline/kaigan/takashioshinsui_manual.pdf]

* [[[mlit_int_flood_guidelines,13]]]
span:organization[国土交通省　水管理・国土保全局　下水道部]
span:title[内水浸水想定区域図作成マニュアル（案）]
span:date[2021-07]
span:uri.citation[https://www.mlit.go.jp/river/shishin_guideline/pdf/naisui_manual.pdf]

* [[[inspire_data_spec,14]]]
span:organization[European Commission Joint Research Centre]
span:title[D2.8.III.6 INSPIRE Data Specification on Utility and Government Services -- Technical Guidelines]
span:date[2013-01-10]
span:uri.citation[https://inspire.ec.europa.eu/Themes/136/2892]
span:language[en]

* [[[ogc_23-024,OGC 23-024]]],
span:organization[Open Geospatial Consortium]
span:title[OGC Model for Underground Data Definition and Integration (MUDDI) Part 1: Conceptual Model]
span:docid.OGC[OGC 23-024]
span:date[2024-01-31]
span:uri.citation[https://portal.ogc.org/files/106383]
span:language[en]

* [[[ifc_bridge_wp2,16]]]
span:title[IFC Bridge Fast Track Project -- Report WP2: Conceptual Model]
span:organization[buildingSMART International]
span:date[2018-10-02]
span:uri.citation[https://www.buildingsmart.org/standards/domains/infrastructure/ifc-bridge/]
span:language[en]

* [[[iana_media_types,amend(IANA media-types)]]] span:language[en]

* [[[mlit_emergency_roads,1]]]
span:title[緊急輸送道路]
span:organization[国土交通省]
span:uri.citation[https://www.mlit.go.jp/road/bosai/measures/index3.html]

* [[[mlit_local_disaster,1]]]
span:title[地域防災計画の作成の基準]
span:organization[国土交通省　水管理・国土保全局　防災課]
span:uri.citation[https://www.mlit.go.jp/common/001618459.pdf]

* [[[mlit_road_upkeep,1]]]
span:title[道路保守・管理]
span:organization[国土交通省　道路局]
span:uri.citation[https://www.mlit.go.jp/road/soudan/soudan_08b_01.html]

* [[[gsi_building_data_manual,1]]]
span:title[建物三次元データ作成マニュアル（案）]
span:organization[国土交通省　国土地理院]
span:date[2016-03]
span:uri.citation[https://www.gsi.go.jp/kankyochiri/Laser_gijutusiryo.html]

* [[[nlftp,1]]]
span:title[国土数値情報]
span:organization[国土交通省　政策統括官付　地理空間情報課]
span:date[2024]
span:uri.citation[https://nlftp.mlit.go.jp]

* [[[mlit_cyberport,1]]]
span:title[Cyber Port サイバーポート]
span:organization[国土交通省]
span:date[2024]
span:uri.citation[https://www.cyber-port.mlit.go.jp]

* [[[mlit_road_damage_map,1]]]
span:title[全国道路施設点検データベース 損傷マップ]
span:organization[国土交通省]
span:date[2024]
span:uri.citation[https://road-structures-map.mlit.go.jp]

* [[[mlit_city_plan_investigation,1]]]
span:title[都市計画現況調査]
span:organization[国土交通省　都市局　都市計画課　都市計画調査室]
span:date[2023]
span:uri.citation[https://www.mlit.go.jp/toshi/tosiko/genkyou.html]

* [[[inspire_registry,1]]]
span:title[INSPIRE registry]
span:organization[European Commission, Joint Research Centre]
span:date[2024]
span:uri.citation[https://inspire.ec.europa.eu/registry]
span:language[en]

* [[[jp_road_law,1]]]
span:title[道路法（昭和二十七年法律第百八十号）]
span:organization[日本国政府]
span:date[1952-06-10]
span:uri.citation[https://elaws.e-gov.go.jp/document?lawid=327AC1000000180]

* [[[jp_building_law,1]]]
span:title[建築基準法（昭和二十五年法律第二百一号）]
span:organization[日本国政府]
span:date[1950-05-24]
span:uri.citation[https://elaws.e-gov.go.jp/document?lawid=325AC0000000201]

* [[[jp_water_prevention_law,1]]]
span:title[水防法（昭和二十四年法律第百九十三号）]
span:organization[日本国政府]
span:date[1949-06-04]
span:uri.citation[https://elaws.e-gov.go.jp/document?lawid=324AC0000000193]

* [[[uniclass,1]]]
span:title[Uniclass]
span:organization[NBS Enterprises Ltd]
span:date[2024]
span:uri.citation[https://uniclass.thenbs.com]
span:language[en]

* [[[jis_x_7107,JIS X 7107]]]

* [[[mlit_urban_digitization,1]]]
span:title[都市計画情報のデジタル化・オープン化ガイダンス]
span:organization[国土交通省　都市局]
span:edition[1.0]
span:date[2024-06]
span:uri.citation[https://www.mlit.go.jp/toshi/tosiko/genkyou.html]

* [[[jswa_sewage_system,1]]]
span:title[下水道台帳管理システム標準仕様（案）・導入の手引き]
span:organization[日本下水道協会]
span:version[5]
span:date[2021-09]
span:uri.citation[https://www.jswa.jp/publication/list/]

* [[[stat_regional_mesh,1]]]
span:title[地域メッシュ統計について]
span:organization[総務省　統計局]
span:date[2024-03-14]
span:uri.citation[https://www.stat.go.jp/data/mesh/m_tuite.html]

* [[[cbr_road_build_manual,1]]]
span:title[道路施設台帳作成マニュアル]
span:organization[国土交通省　中部地方整備局]
span:date[2009-03]
span:edition[1.3]
span:uri.citation[https://www.cbr.mlit.go.jp/architecture/kensetsugijutsu/download/index.htm]

* [[[real_estate_id_guidelines,1]]]
span:title[不動産 ID ルールガイドライン]
span:organization[国土交通省　不動産　建設経済局]
span:date[2022-03-31]
span:uri.citation[https://www.mlit.go.jp/tochi_fudousan_kensetsugyo/content/001594268.pdf]

* [[[maff_reservoir_hazard_maps,18]]]
span:title[ため池ハザードマップ作成の手引き]
span:organization[農林水産省　農村振興局　防災課]
span:date[2013-05]
span:uri.citation[https://www.maff.go.jp/j/nousin/bousai/bousai_saigai/b_tameike/pdf/tameike_manual_1rev.pdf]

* [[[sig3d_model_1,1]]]
span:title[Modeling Guide for 3D Objects Part 1: Basics (Rules for Validating GML Geometrics in CityGML)]
span:organization[SIG3D]
span:date[2014-11]
span:uri.citation[https://www.sig3d.org/files/media/downloads/SIG3D/AG-Qualitaet/201311_SIG3D_Modeling_Guide_for_3D_Objects_Part_1.pdf]
span:language[en]

* [[[sig3d_model_2,1]]]
span:title[Modeling Guide for 3D Objects Part 2: Modeling of Buildings (LoD1, LoD2 and LoD3)]
span:organization[SIG3D]
span:date[2014-11]
span:uri.citation[https://www.sig3d.org/files/media/downloads/SIG3D/AG-Qualitaet/201311_SIG3D_Modeling_Guide_for_3D_Objects_Part_2.pdf]
span:language[en]

* [[[plateau_000,PLATEAU Handbook #00]]],
span:title[3D都市モデルの導入ガイダンス]
span:organization[国土交通省　都市局]
span:docid.PLATEAU[PLATEAU Handbook #00]
span:edition[5.0]
span:date[2023-04-07]
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/handbooks/]

* [[[plateau_tr_03,PLATEAU Technical Report #03]]]
span:title[3D都市モデルLOD3データ作成実証レポート]
span:organization[国土交通省　都市局]
span:docid.PLATEAU[PLATEAU Technical Report #03]
span:edition[1.0]
span:date[2022-03-29]
span:uri.citation[https://www.mlit.go.jp/plateau/file/libraries/doc/plateau_tech_doc_0003_ver01.pdf]

* [[[plateau_tr_56,PLATEAU Technical Report #56]]]
span:title[AI等を活用したLOD2自動生成ツールの開発及びOSS化 技術検証レポート]
span:organization[国土交通省　都市局]
span:docid.PLATEAU[PLATEAU Technical Report #56]
span:edition[1.0]
span:date[2023-04-04]
span:uri.citation[https://www.mlit.go.jp/plateau/file/libraries/doc/plateau_tech_doc_0056_ver01.pdf]

* [[[ogc_19-081,amend(OGC 19-081)]]] span:language[en]

* [[[tunnel_diagram_oonabe,1]]]
span:title[雄勝地区トンネル詳細設計業務　設計図　【大鍋トンネル】（国道13号）]
span:organization[中央復建コンサルタンツ株式会社]
span:date[2020-03]
span:uri.citation[https://www.thr.mlit.go.jp/road/kouji/kouji-tunnel/tunnel-index.html]
// https://www.thr.mlit.go.jp/road/kouji/kouji-tunnel/24_R13_oonabe/data_05_.pdf

* [[[tunnel_diagram_asakawa,1]]]
span:title[令和2年度　平石地区トンネル詳細設計業務　設計図　【本坑（上線）】（国道13号）]
span:organization[東北地方整備局　福島河川国道事務所]
span:organization[セントラルコンサルタント株式会社]
span:date[2023-03]
span:uri.citation[https://www.thr.mlit.go.jp/road/kouji/kouji-tunnel/tunnel-index.html]
// https://www.thr.mlit.go.jp/road/kouji/kouji-tunnel/29_R13_asakawa/data_05.pdf

* [[[cbr_road_sample_data,1]]]
span:title[道路施設台帳サンプルデータ]
span:organization[国土交通省　中部地方整備局]
span:date[2017-03-14]
span:uri.citation[https://www.cbr.mlit.go.jp/architecture/kensetsugijutsu/download/index.htm]

* [[[jpgis_2014,JPGIS 2014]]],
span:title[地理情報標準プロファイル（JPGIS）2014]
span:organization[国土交通省　国土地理院]
span:uri.citation[https://www.gsi.go.jp/GIS/jpgis-downloads.html]

* [[[jpgis_v1,JPGIS 解説書 1.0]]],
span:title[地理情報標準プロファイル（JPGIS） Ver. 1.0　解説書]
span:organization[国土交通省　国土地理院]
span:uri.citation[https://www.gsi.go.jp/GIS/jpgis-rh.html]

* [[[gsi_ops,作業規程の準則]]],
span:title[作業規程の準則]
span:organization[国土交通省　国土地理院]
span:uri.citation[https://www.gsi.go.jp/gijyutukanri/gijyutukanri41018.html]

* [[[jmp20,JMP 2.0]]],
span:title[JMP 2.0仕様書]
span:organization[国土交通省　国土地理院]
span:uri.citation[https://www.gsi.go.jp/GIS/jpgis-downloads.html]

* [[[jpgis_spec_reqs,JPGIS 品質の要求　評価及び報告のための規則]]],
span:title[品質の要求，評価及び報告のための規則]
span:organization[国土交通省　国土地理院]
span:uri.citation[https://www.gsi.go.jp/GIS/jpgis-downloads.html]

* [[[city_data_ps_sample,dropid(1)]]],
span:title[都市計画データ標準製品仕様書]
span:organization[国土交通省　都市局]
span:uri.citation[https://www.mlit.go.jp/toshi/tosiko/toshi_tosiko_tk_000187.html]

* [[[nilim_kiban_dps,道路基盤地図情報（整備促進版）製品仕様書（案）]]],
span:title[道路基盤地図情報（整備促進版）製品仕様書（案）]
span:organization[国土交通省　国土技術政策総合研究所]
span:date[2014-05]
span:uri.citation[https://www.nilim.go.jp/lab/bcg/siryou/tnn/tnn0848pdf/ks084811.pdf]

* [[[gsi_map_level_dps,地図情報レベル 2500 数値地形図データ作成のための標準製品仕様書（案）]]],
span:title[地図情報レベル 2500 数値地形図データ作成のための標準製品仕様書（案）]
span:organization[国土交通省　国土地理院]
span:uri.citation[https://www.gsi.go.jp/common/000259076.pdf]

* [[[iconstruction,i-Construction推進]]],
span:title[i-Construction推進のための3次元数値地形図データ作成マニュアル]
span:organization[国土交通省　国土地理院]
span:uri.citation[https://www.gsi.go.jp/gijyutukanri/gijyutukanri41029.html]

* [[[plateau_003,PLATEAU Handbook #03]]],
span:title[3D都市モデル整備のためのBIM活用マニュアル]
span:organization[国土交通省　都市局]
span:docid.PLATEAU[PLATEAU Handbook #03]
span:edition[4.0]
span:date[2023-03-27]
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/handbooks/]

* [[[plateau_003_annex,PLATEAU Handbook #03-1]]],
span:title[3D都市モデル整備のためのBIM活用マニュアル（第3.0版）（別冊）3D都市モデルとの連携のためのBIMモデルIDM・MVD]
span:organization[国土交通省　都市局]
span:docid.PLATEAU[PLATEAU Handbook #03-1]
span:edition[2.0]
span:date[2023-03-27]
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/handbooks/]

* [[[ifc_2x3_cv,IFC2x3 CV2.0]]],
span:title[IFC 2x3 Coordination View 2.0]
span:organization[buildingSMART International]
span:uri.citation[https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/FINAL/HTML/]

* [[[gsi_dps,3次元屋内地理空間情報データ仕様書（案）]]],
span:title[3次元屋内地理空間情報データ仕様書（案）]
span:organization[国土交通省　国土地理院]
span:uri.citation[https://www.gsi.go.jp/common/000212582.pdf]

* [[[iso_19106_2004,ISO 19106:2004]]]

* [[[mlit_kiban_chizu,河川基盤地図ガイドライン（案）]]]
span:title[河川基盤地図ガイドライン（案）]
span:organization[国土交通省　都市局]
span:edition[2.1]
span:date[2001-12]
span:uri.citation[https://www.mlit.go.jp/river/shishin_guideline/kasen/gis/pdf_docs/chizu/kiban_chizu.pdf]

* [[[gsi_foundation_map_dps,電子国土基本図地図情報ファイル仕様書]]]
span:title[電子国土基本図地図ファイル仕様書]
span:edition[1.1]
span:organization[国土交通省　国土地理院]
span:date[2017-06-30]
span:uri.citation[https://www.gsi.go.jp/common/000189294.pdf]

* [[[mlit_tide_flood_map,高潮浸水想定区域図作成の手引き]]]
span:title[高潮浸水想定区域図作成の手引き]
span:edition[2.11]
span:organization[国土交通省　国土地理院]
span:date[2017-06-30]
span:uri.citation[https://www.mlit.go.jp/river/shishin_guideline/kaigan/takashioshinsui_manual.pdf]

* [[[plateau_010,PLATEAU Handbook #10]]],
span:organization[国土交通省　都市局]
span:title[3D都市モデル整備のための測量マニュアル]
span:docid.PLATEAU[PLATEAU Handbook #10]
span:date[2024-04-02]
span:edition[4.1]
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/]

* [[[ogc_19-008r4,OGC 19-008r4]]],
span:title[OpenGIS® OGC GeoTIFF Standard, Version 1.1]
span:organization[Open Geospatial Consortium]
span:docid.OGC[OGC 19-008r4]
span:uri.citation[http://www.opengis.net/doc/IS/GeoTIFF/1.1]
span:language[en]

* [[[mlit_foundation_reqs,都市計画基礎調査実施要領]]],
span:title[都市計画基礎調査実施要領]
span:organization[国土交通省　都市局]
span:edition[5]
span:uri.citation[https://www.mlit.go.jp/toshi/tosiko/kisotyousa001.html]

* [[[iso_19101,amend(ISO 19101)]]] span:language[en]