[[tocL_06]]
=== brid:BridgeInstallation

brid:BridgeInstallationは、橋梁本体の外側又は内側に設置され、橋梁の構造を特徴づける恒久的な設備を記述するために用いる。橋梁の付帯的な設備であり、主要な部分であってはならない。

橋梁の付属物には以下を含む。ただし、全て橋梁と接するもののみを対象とする。 +
支承、落橋防止装置、伸縮装置、排水施設、高欄、防護柵、遮音壁、遮光壁、点検施設、航空障害灯、アンテナ、看板、階段、手すり、外階段・歩道の庇、スロープ、輸送設備（エレベータ、エスカレータ、動く歩道）、柱、デッキ、ステージ、パネル、梁、その他

ただし、ユースケースの要求に応じて、取得対象とする付属物を限定してもよく、また、付属物として取得せず橋梁の一部として取得してもよい。


[[tocL_06_01]]
==== 橋梁付属物の空間属性

[[tocL_06_01_01]]
===== 橋梁付属物の屋内外の区分

brid:BridgeInstallationは、橋梁の外側に設置される場合と、橋梁の内側に設置される場合とある。 +
brid:BridgeInstallationの外部・内部の区分は、属性con:relationToConstructionにより行う。この属性は、上位の地物型であるcon:AbstractInstallationから継承する。 +
属性con:relationToConstructionの値は、列挙型であるcon:RelationToConstructionにより定義される。

* inside：この付属物は、橋梁の内部に存在する。
* outside：この付属物は、橋梁の外部に存在する。
* bothInsideAndOutside：この付属物は、橋梁の内部と外部の両方に存在する。


[[tocL_06_01_02]]
===== LOD0

brid:BridgeInstallationは多曲面（core:lod0MultiSurface）として表現する。


[[tocL_06_01_03]]
===== LOD1

brid:BridgeInstallationは立体（core:lod1Solid）として表現する。


[[tocL_06_01_04]]
===== LOD2

brid:BridgeInstallationは多曲面（core:lod2MultiSurface）として表現する。


[[tocL_06_01_05]]
===== LOD3

brid:BridgeInstallationは多曲面（core:lod3MultiSurface）として表現する。


[requirement]
.brid:BridgeInstallationの空間属性タイプ
====
[%metadata]
identifier:: /req/brid/8
subject:: 妥当な橋梁データセットの要件
description:: brid:BridgeInstallationの空間属性の型は、LODに応じた型を選択する。
part:: LOD0：gml:MultiSurfaceを使用する。
part:: LOD1：gml:Solidとする。
part:: LOD2：gml:MultiSurfaceを使用する。
part:: LOD3：gml:MultiSurfaceを使用する。
====

ある程度の広がりをもつ地物は、多曲面又は立体を使用する。CityGMLでは、面や立体だけではなく、点や多曲線（線の集まり）も使用可能である。しかしながら3D都市モデルでは、3次元での利用を想定し、付属物の形状に使用可能な幾何オブジェクトを多曲面又は立体に限定する。

LOD1の場合は、立体（gml:Solid）を使用しなければならない。LOD0、LOD2及びLOD3は、（gml:MultiSurface）を使用する。

