[[tocL_04]]
=== brid:BridgePart

brid:BridgePartは、橋梁の一部であり、橋梁モデルにおいて、一つの橋梁を複数の部分に分けて記述するために用いる。一つの橋梁を複数の部分に分けて記述する場合とは、以下をいう。

* 一つの橋梁を、主題属性の異なる複数の部分に分ける場合

例えば、一つの橋梁が、構造の異なる複数の径間から構成されている場合、それぞれをbrid:BridgePartとして作成し、それらを束ねたbrid:Bridgeを作成することで、一つの橋梁として表現できる。

また、一つの橋梁を構径間ごとに異なる原典資料を使用し、品質が異なるデータとなっている場合には、それぞれをbrid:BridgePartとして作成し、brid:BridgePartごとに使用した原典資料や地図情報レベルを属性として記録することができる。


[[tocL_04_01]]
==== 橋梁部分の空間属性

brid:BridgePartの空間属性は、brid:Bridgeの空間属性の取得方法と同じである。 +
なお、連続するbrid:BridgePartの境界面は、core:ClosureSurfaceとなる。


[[tocL_04_02]]
==== 橋梁部分の主題属性

brid:BridgePartは、brid:Bridgeと同様の主題属性をもつことができる。必要に応じてbrid:BridgePartごとに個別の属性をもつ。

brid:BridgePartはデータ品質属性（urc:DataQualityAttribute）をもつことができる。この場合、これを部品とするbrid:Bridgeはデータ品質属性をもたない。

また、データ品質属性の各属性には、brid:BridgePartのデータ作成に使用した原典資料の地図情報レベル、その他原典資料の諸元を記述することが基本となる。ただし、urc:geometrySrcDescLod0等のLOD0の幾何オブジェクトについての属性は、このbrid:BridgePartを部品としてもつbrid:BridgeのLOD0の幾何オブジェクトに対応する値を記述する。

なお、brid:Bridgeの部品となる全てのbrid:BridgePartについて、データ品質属性の値が全て等しくなる場合は、brid:Bridgeにデータ品質属性を記述することができる。このとき、部品となる各brid:BridgePartはデータ品質属性をもたない。

