[[tocL_08]]
=== brid:BridgeFurniture

brid:BridgeFurnitureは、橋梁内部の空間に配置された可動設備を記述するために用いる地物型である。brid:BridgeInstallationが恒久的かつ固定的な設備であることと対照的に、brid:BridgeFurnitureは椅子や机のような動かすことができる（位置が固定されない）設備である。

ユースケースの要求に応じて、取得対象とする可動設備を決定してよい。

brid:BridgeFurnitureは、橋梁モデル・内部においてのみ使用できる地物型である。


[[tocL_08_01]]
==== 可動設備の空間属性


[[tocL_08_01_01]]
===== LOD0

brid:BridgeFurnitureは多曲面（core:lod0MultiSurface）として表現する。


[[tocL_08_01_02]]
===== LOD1

brid:BridgeFurnitureは立体（core:lod1Solid）として表現する。


[[tocL_08_01_03]]
===== LOD2

brid:BridgeFurnitureは多曲面（core:lod2MultiSurface）として表現する。


[[tocL_08_01_04]]
===== LOD3

brid:BridgeFurnitureは多曲面（core:lod3MultiSurface）として表現する。


[requirement]
.brid:BridgeFurnitureの空間属性タイプ
====
[%metadata]
identifier:: /req/brid/9
subject:: 妥当な橋梁データセットの要件
description:: brid:BridgeFurnitureの空間属性の型には、LODに応じた型を選択する。
part:: LOD0：gml:MultiSurfaceを使用する。
part:: LOD1：gml:Solidとする。
part:: LOD2：gml:MultiSurfaceを使用する。
part:: LOD3：gml:MultiSurfaceを使用する。
====

ある程度の広がりをもつ地物は、曲面の集まり又は立体を使用する。CityGMLでは、曲面や立体だけではなく、点や曲線も使用可能である。しかしながら3D都市モデルでは、3次元での利用を想定し、可動設備の形状に使用可能な幾何オブジェクトを曲面又は立体に限定する。

LOD1の場合は、立体（gml:Solid）を使用しなければならない。LOD0、LOD2及びLOD3は、多曲面（gml:MultiSurface）を使用する。


