[[tocL_03]]
=== brid:Bridge

brid:Bridgeは、橋梁の記述に使用する地物型である。


[[tocL_03_01]]
==== 橋梁の空間属性

brid:Bridgeの空間属性には、LOD0からLOD3までの4つがある。これらは、いずれも橋梁の外部の形状を表す。


[[tocL_03_01_01]]
===== LOD0

brid:Bridgeの空間属性は、LOD0において、面（core:lod0MultiSurface）により表現する。 +
このとき、橋梁オブジェクトは、橋梁モデル・外部（LOD0）の定義に従ったものでなければならない。


[requirement]
.橋梁のLOD0形状定義
====
[%metadata]
identifier:: /req/brid/2
subject:: 妥当な橋梁データセットの要件
description:: 橋梁のLOD0の形状は、橋梁モデル・外部（LOD0）の定義に従う。
====

橋梁は、LOD0において外周を面として取得する。 +
「<<gsi_ops,作業規程の準則 付録７ 公共測量標準図式>>」（以下、「公共測量標準図式」という）に従った記述を行いたい場合は、数値地形図属性（urc:DmAttribute）を使用する。


[[tocL_03_01_02]]
===== LOD1

brid:Bridgeの空間属性は、LOD1において、立体（core:lod1Solid）により記述する。このとき、橋梁オブジェクトは、橋梁モデル・外部（LOD1）の定義に従ったものでなければならない。


[requirement]
.橋梁のLOD1形状定義
====
[%metadata]
identifier:: /req/brid/3
subject:: 妥当な橋梁データセットの要件
description:: 橋梁のLOD1の形状は、橋梁モデル・外部（LOD1）の定義に従う。
====

道路橋及び鉄道橋は、橋梁の縁線をつないだ外周を、地表面から一律の高さで下向きに押し出した立体とする。ひ開部は含めない。橋梁モデル（LOD0）に橋脚の外周が含まれている場合は、橋脚を含めた外周に一律の高さを与える。

桟道橋は、縁線、斜面に接している側の道路縁及び橋脚の外周を含む桟道橋の外周に、地表面から一律の高さで下向きに押し出した立体とする。

横断歩道橋、跨線橋及びペデストリアンデッキは、構造物の上からの正射影の外周を、地表面から一律の高さで上向きに押し出した立体とする。幅員が1m以上の徒橋は、縁線をつないだ外周を地表面から一律の高さで下向きに押し出した立体とする。


[requirement]
.lod1Solidの立体定義
====
[%metadata]
identifier:: /req/brid/4
subject:: 妥当な橋梁データセットの要件
description:: core:lod1Solidで示される立体は、橋梁の縁線をつないだ外周を、地表面から一律の高さ下向き又は上向きに押し出した立体とする。
====


[[tocL_03_01_03]]
===== LOD2

brid:Bridgeの空間属性は、LOD2において、面（core:lod2MultiSurface）又は立体（core:lod2Solid）により表現する。 +
このとき、橋梁オブジェクトは、橋梁モデル・外部（LOD2）の定義に従ったものでなければならない。


[requirement]
.橋梁のLOD2形状定義
====
[%metadata]
identifier:: /req/brid/5
subject:: 妥当な橋梁データセットの要件
description:: 橋梁のLOD2の形状は、橋梁モデル・外部（LOD2）の定義に従う。
====

橋梁モデル・外部（LOD2）は、LOD2.0及びLOD2.1に細分される。LOD2.0では、橋梁の形状を面の集まりとして表現し、LOD2.1では、橋梁の形状を立体として表現する。


[[tocL_03_01_04]]
===== LOD3

brid:Bridgeの空間属性は、LOD3において、面（core:lod3MultiSurface）又は立体（core:lod3Solid）により表現する。 +
このとき、橋梁オブジェクトは、橋梁モデル・外部（LOD3）の定義に従ったものでなければならない。


[requirement]
.橋梁のLOD3形状定義
====
[%metadata]
identifier:: /req/brid/6
subject:: 妥当な橋梁データセットの要件
description:: 橋梁のLOD3の形状は、橋梁モデル・外部（LOD3）の定義に従う。
====

橋梁のLOD3は、構造部材を構成する面を集めた多曲面又は立体として表現される。橋梁モデル・外部（LOD3）では、橋梁は、構造部材の集まりとなり、橋梁の多曲面又は立体を構成する面は、構造部材の空間属性に含まれる面と一致する。


[[tocL_03_02]]
==== 橋梁の主題属性

橋梁の主題属性には、あらかじめCityGML又はGMLにおいて定義された属性（接頭辞bridのほか、gml、core、gen、conが登場しうる）と、i-URにより拡張された属性（接頭辞urc、uro）がある。CityGMLで定義された属性は、橋梁の機能など、基本的な情報となる。

i-URにより拡張された属性には、大きく10種類の属性がある。橋梁の管理に関する基本的な情報（uro:ConstructionBaseAttribute）、橋梁の構造に関する情報（uro:BridgeStructureAttribute）、橋梁の機能に関する情報（brid::BridgeFunctionalAttribute）、橋梁の損傷に関する情報（uro:ConstructiondRiskAssessmentAttribute）がある。

また、上位の地物型から継承する属性には災害リスク情報を格納するための属性（urc:DisasterRiskAttribute）、作成したデータの品質に関する情報を格納するための属性（urc:DataQualityAttribute）、また、公共測量標準図式に従った表現に必要となる属性（urc:DmAttribute）がある。 +
さらに、特定分野での施設管理に使用する属性として、施設区分に関する属性（uro:FacilityTypeAttribute）、その分野における施設の位置や識別に関する属性（uro:FacilityIdAttribute）、その分野における施設の詳細な属性（uro:FacilityAttribute）などをもつことができる。


[[tocL_03_02_01]]
===== 構造物管理属性（uro:ConstructionBaseAttribute）

橋梁の管理者や建設に関する諸元等、橋梁の管理に必要な基本的な情報。


[[tocL_03_02_02]]
===== 橋梁構造属性（uro:BridgeStructureAttribute）

橋梁の延長や幅員など、橋梁の構造に関する情報。


[[tocL_03_02_03]]
===== 橋梁機能属性（uro:BridgeFunctionalAttribute）

橋梁の利用者や進行方向。


[[tocL_03_02_04]]
===== 構造物損傷属性（uro:ConstructionRiskAssessmentAttribute）

構造物の損傷及び対応状況に関する情報。


[[tocL_03_02_05]]
===== 災害リスク属性（uro:DisasterRiskAttribute）

浸水想定区域や土砂災害警戒区域等の災害リスクに関する情報。


[[tocL_03_02_06]]
===== 施設管理のための属性

施設管理のための属性は、港湾施設及び漁港施設、河川管理施設や公園管理施設等の施設管理に必要な情報を定義した属性である。施設管理のための属性は以下のデータ型を用いて記述する。


[[tocL_03_02_06_01]]
====== 施設分類属性（uro:FacilityTypeAttribute）

uro:FacilityTypeAttributeは、各分野で定める施設の区分を記述するためのデータ型である。CityGMLは、地物型を物体としての性質に着目して定義し、機能や用途は属性で区分している。

例えば、「橋梁（brid:Bridge）」という地物型を定義し、属性functionにより「道路橋」や「鉄道橋」を区分している。これにより、都市に存在する様々な地物を、分野を問わず網羅的に、かつ、矛盾が無く表現することを目指している。

一方、各分野には独自の施設の区分がある。この区分は当該分野での施設管理に必要な情報であるが、CityGMLの地物型の区分とは一致しない。そこで、これらの地物型に分野独自の区分を付与するためにこのデータ型を用いる。uro:FacilityTypeAttributeは、二つの属性をもつ。uro:classは分野を特定するための属性である。またuro:functionは、uro:classにより特定した分野における施設の区分を示す。

標準製品仕様書では、港湾施設、漁港施設及び公園施設については標準製品仕様書においてuro:functionの区分が示されている。その他の区分についてはuro:classへの分野の追加も含め、拡張製品仕様書において拡張できる。


[[tocL_03_02_06_02]]
====== 施設識別属性（uro:FacilityIdAttribute）

uro:FacilityIdAttributeは、施設の位置を特定する情報及び施設を識別する情報を記述するためのデータ型である。uro:FacilityIdAttributeは、施設を識別するための情報として、識別子（uro:id）や正式な名称以外の呼称（uro:alternativeName）に加え、施設の位置を示すための、都道府県（uro:prefecture）、市区町村（uro:city）及び開始位置の経緯度（uro:startLat、uro:startLong）を属性としてもつ。また、鉄道上や道路上の施設については、路線や距離標での位置特定のための属性（uro:route、uro:startPost、uro:endPost）を使用できる。

なお、河川管理施設の場合は、uro:FacilityIdAttributeを継承するuro:RiverFacilityIdAttributeを使用する。これにより、左右岸上での位置の情報を記述できる。


[[tocL_03_02_06_03]]
====== 施設詳細属性（uro:FacilityAttribute）

uro:FacilityAttributeは、各分野において施設管理に必要となる情報を記述するためのデータ型である。uro:FacilityAttributeは、抽象クラスであり、これを継承する具象となるデータ型に、施設の区分毎に必要となる情報を属性として定義している。

標準製品仕様書では、港湾施設、漁港施設及び公園施設について、細分した施設の区分ごとにデータ型を定義している。また、施設に関する工事や点検の状況や内容を記述するためのデータ型（uro:MaintenanceHistoryAttribute）を定義している。


[[tocL_03_02_07]]
===== 数値地形図属性（urc:DmAttribute）

公共測量標準図式に従った形状表現に必要な情報を格納するための属性である。LOD0の幾何オブジェクトのほか、数値地形図との互換性を保つために必要な情報が、属性として定義されている。

[[tocL_03_02_08]]
===== データ品質属性（urc:DataQualityAttribute）

橋梁の3D都市モデルを作成する場合、様々な原典資料を組み合わせて作成することが想定される。例えば、地図情報レベル2500の数値地形図を用いてLOD1の橋梁を都市全域で作成したが、一部の地域についてはより新しい航空写真が得られたため、これを用いて図化する、又は一つの橋梁であっても、上面は地図情報レベル2500の航空写真からの図化により作成し、橋台は竣工図等からのマップデジタイズにより作成することが考えられる。 +
位置正確度の異なる原典資料を用いて作成した3D都市モデルを作成した場合、位置正確度の異なる橋梁一つのデータセット内に混在することになる。同様にして、異なる原典資料を使用したことにより、同じデータセット内のLOD2の橋梁であっても屋根形状のみしか再現されていない橋梁と付属物や開口部まで取得された橋梁とが混在する可能性がある。 +
3D都市モデルでは、データセット全体としての品質はメタデータに記録する。しかしながら、メタデータでは、個々の橋梁に対して位置正確度や適用したLOD等の品質を記述することが困難である。

そこで、標準製品仕様書では、個々の橋梁に対してデータ品質に関する情報を記述するための属性として、「データ品質属性」（urc:DataQualityAttribute）を定義している。データ品質属性は、属性としてデータ作成に使用した原典資料の地図情報レベル、その他原典資料の諸元、精緻化したLOD、LOD1の押し出しに使用する高さ（<<tocC_03_02_11>>）等をもつ。

このデータ品質属性は、外部のモデルに適用するurc:ExteriorDataQualityAttributeと内部のモデルに適用するurc:InteriorDataQualityAttributeに分かれる。 +
外部モデルを作成する場合にはurc:ExteriorDataQualityAttributeを使用し、内部モデルを作成する場合は、urc:InteriorDataQualityAttributeを使用する。 +
外部・内部の両方のモデルを作成した場合には、urc:ExteriorDataQualityAttributeとurc:InteriorDataQualityAttributeの両方を記述する。

3D都市モデルに含まれる全ての橋梁オブジェクトは、直接またや間接的にデータ品質属性をもたなければならない。原則としてbrid:Bridgeがもち、橋梁の部分ごとに品質が異なる場合には、brid:BridgePartがもつ。brid:BridgePartがデータ品質属性をもつ場合、brid:Bridgeはもたない。また、橋梁（brid:Bridge）又はその部分（brid:BridgePart）を構成する部品（例：con:AbstractConstructionSurface）にはデータ品質属性を付与することはできない。

* geometrySrcDescLODX（Xには、0から3までの数字が入る。）：指定したLODの幾何オブジェクトの作成に使用した原典資料の種類をコードリストから選択する。公共測量成果を使用する場合には、原典資料の地図情報レベルや原典資料の種類を記録するためのPublicSurveyDataQualityAttributeを作成しなければならない。
* appearanceSrcDescLODX（Xには、0から3までの数字が入る。）：指定したLODの幾何オブジェクトのアピアランスに使用した原典資料の種類をコードリストから選択する。
* thematicSrcDesc：主題属性の作成に使用した原典資料の種類をコードリストから選択する。
* lod1HeightType：LOD1の立ち上げに使用した高さの種類。
* lodType：幾何オブジェクトに適用されたLODの詳細な区分。LODごとに指定しなければならない。
* granularity：開口部の取得有無をコードリストから選択する。
* hasError：LOD0の幾何オブジェクトに原典資料に由来するエラーが存在しており、これを修正していない場合にエラー内容をコードリストから選択する。
* lod0AcquisitionCriterion：橋梁モデルでは使用しない。
* tranDataAcquisition：原典資料の詳細。橋梁が道路施設の場合にのみ使用する。


[[tocL_03_02_09]]
===== ADEで拡張された属性の記述

CityGML3.0では、地物型ごとに、属性を拡張するためのデータ型ADEOfXXX（XXXには地物型の名称が入る）が用意されている。また、拡張したデータ型を地物の属性として記述するための主題属性adeOfXXX（XXXには地物型の名称が入る）も用意されている。例えば、建築物（Building）という地物型に属性を追加したい場合、ADEOfBuildingを使う。このデータ型を継承して新しい属性を定義することで、主題属性adeOfBuildingの型として記述できるようになる。

ここで、橋梁の<<tocL_03_02_02,橋梁構造属性>>、<<tocL_03_02_01,構造物管理属性>>、<<tocL_03_02_08,データ品質属性>>、<<tocL_03_02_07,数値地形図属性>>等の主題属性は、上述の仕組みを使って拡張して定義されたデータ型である。これらのデータ型を記述する場合には、拡張した地物型に対応する主題属性adeOfXXX（XXXには地物型の名称が入る）の型として記述しなければならない。

例えば、橋梁に特化した情報である、<<tocL_03_02_02,橋梁構造属性>>はADEOfAbstractBridgeを継承して定義されているため、adeOfAbstractBridgeの型として記述する。また、<<tocL_03_02_01,構造物管理属性>>は、ADEOfAbstractConstructionを継承しているため、adeOfAbstractConstructionの型として記述する。さらに、<<tocL_03_02_08,データ品質属性>>は、ADEOfAbstractCityObjectを継承して定義されているため、adeOfAbstractCityObjectの型として記述する。

このように、ADEで拡張された属性が、どの地物型を拡張して定義されているかによって、主題属性として値を記述する場所が異なることに注意が必要である。

