[[tocN_03]]
=== con:OtherConstruction

con:OtherConstructionは、その他の構造物の記述に使用する地物型である。


[[tocN_03_01]]
==== その他の構造物の空間属性


[[tocN_03_01_01]]
===== LOD0

con:OtherConstructionの空間属性は、LOD0において、面（core:lod0MultiSurface）により表現する。 +
このとき、その他の構造物オブジェクトは、その他の構造物モデル（LOD0）の定義に従ったものでなければならない。


[requirement]
.その他の構造物のLOD0形状定義
====
[%metadata]
identifier:: /req/cons/2
subject:: 妥当なその他の構造物データセットの要件
description:: その他の構造物のLOD0の形状は、その他の構造物モデル（LOD0）の定義に従う。
====


[[tocN_03_01_02]]
===== LOD1

con:OtherConstructionの空間属性は、LOD1において、構造物の上方からの正射影の外周に一律の高さを与えて上向きに押し出した立体（core:lod1Solid）により表現する。 +
このとき、その他の構造物オブジェクトは、その他の構造物モデル（LOD1）の定義に従ったものでなければならない。


[requirement]
.その他の構造物のLOD1形状定義
====
[%metadata]
identifier:: /req/cons/3
subject:: 妥当なその他の構造物データセットの要件
description:: その他の構造物のLOD1の形状は、その他の構造物モデル（LOD1）の定義に従う。
====

その他の構造物モデル（LOD1）では、con:OtherConstructionの空間属性は、構造物の外周に一律の高さを与えた立体を表現することを基本とする。ただし、水制や床止めのように、同じ形状の小規模な構造物が繰り返し配置され、一体となってその機能を果たす構造物の場合、全体を包含する矩形又は矩形の集まりを面として取得し、一律の高さを与えて上向きに押し出した立体とする。


[[tocN_03_01_03]]
===== LOD2

con:OtherConstructionの空間属性は、LOD2において、立体（core:lod2Solid）により表現する。 +
このとき、その他の構造物オブジェクトは、その他の構造物モデル（LOD2）の定義に従ったものでなければならない。


[requirement]
.その他の構造物のLOD2形状定義
====
[%metadata]
identifier:: /req/cons/4
subject:: 妥当なその他の構造物データセットの要件
description:: その他の構造物のLOD2の形状は、その他の構造物モデル（LOD2）の定義に従う。
====

その他の構造物モデル（LOD2）は、形状の再現度の異なるLOD2.0及びLOD2.1に細分される。

その他の構造物モデル（LOD2.0）では、その他の構造物の形状を、主要な部分を簡略化した立体として表現する。立体は、上空から見た形状を取得し、立体の各境界面を、屋根面（con:RoofSurface）、外壁面（con:WallSurface）、底面（con:GroundSurface）又は閉鎖面（con:ClosureSurface）のいずれかに区分する。

その他の構造物モデル（LOD2.1）では、その他の構造物の形状を立体として表現する。この立体は、主要な部分の外形を構成する特徴点から構成する面を境界面とする。また、立体の各境界面を、屋根面
（con:RoofSurface）、外壁面（con:WallSurface）、底面（con:GroundSurface）又は閉鎖面（con:ClosureSurface）のいずれかに区分する。さらに、構造上不可欠ではない付属物（手すり、柵、構造物と一体ではない階段）を表現することができる。

その他の構造物モデル（LOD2.0）では、上空から見た形状が取得されるため、屋根面は詳細化されるが、外壁面は詳細化されない。

その他の構造物モデル（LOD2.1）では、側面から見た形状も含めて取得されるため、屋根面に加え、外壁面が詳細化される。


[[tocN_03_01_04]]
===== LOD3

con:OtherConstructionの空間属性は、LOD3において、多曲面（core:lod3MultiSurface）により表現する。 +
このとき、その他の構造物オブジェクトは、その他の構造物モデル（LOD3）の定義に従ったものでなければならない。


[requirement]
.その他の構造物のLOD3形状定義
====
[%metadata]
identifier:: /req/cons/5
subject:: 妥当なその他の構造物データセットの要件
description:: その他の構造物のLOD3の形状は、その他の構造物モデル（LOD3）の定義に従う。
====

その他の構造物モデル（LOD3）は、含むべき地物の異なるLOD3.0及びLOD3.1に細分される。

その他の構造物モデル（LOD3.0）は、その他の構造物を構造部材の集まりとして表現し、構造部材を構成する面の組み合わせによりその他構造物の形状を立体又は多曲面として表現する。

その他の構造物モデル（LOD3.1）は、その他の構造物モデル（LOD3.0）によって作成した構造物の形状を構成する各面を、境界面として区分する。

その他の構造物モデル（LOD1）及びその他の構造物モデル（LOD2.0）では、水制や床止めは、一体となって設置された構造物全体をまとめて一つのオブジェクトとして取得される。一方、その他の構造物モデル（LOD2.1）及びその他の構造物モデル（LOD3）では、一つ一つの水制や床止めの形状を表現できる。ただし、一つ一つの水制や床止めを計測してその形状を再現する必要はなく、一つの水制又は床止めのその他の構造物モデルをテンプレートとして作成し、このモデルを配置する座標のみを変更した複製を配置してもよい。


[[tocN_03_02]]
==== その他の構造物の主題属性

その他の構造物の主題属性には、構造物の種類を区分する属性のほか、構造物の管理者や完成年などの基本的な属性（uro:ConstructionBaseAttribute）、構造物の構造に関する属性（uro:ConstructionStructureAttribute）、構造物の位置や識別に関する属性（uro:FacilityIdAttribute）、特定の分野における施設区分に関する属性（uro:FacilityTypeAttribute）、その分野における施設管理に必要な属性（uro:FacilityAttribute）、公共測量標準図式に従った表現に必要となる属性（urc:DmAttribute）及び作成したデータの品質に関する属性（urc:DataQualityAttribute）がある。


[[tocN_03_02_01]]
===== 分類（con:class）、機能（con:function）

その他の構造物には、ダム、堤防、床止め、堰、水門・閘門・陸閘、樋門・樋管、伏せ越し、水制、護岸、防波堤その他の土木構造物が含まれるが、これらの区分は属性classにより行う。また、属性functionにより、細分できる。

標準製品仕様書では、主に河川、港湾、漁港に関する構造物の区分をコードリストに用意しているが、不足する場合には、拡張製品仕様書において拡張できる。


[[tocN_03_02_02]]
===== 構造物管理属性（uro:ConstructionBaseAttribute）

構造物の管理に必要となる基本的な情報及び、構造物の建設に関する基本的な情報を記述する。


[[tocN_03_02_03]]
===== 構造物構造属性（uro:ConstructionStructureAttribute）

構造物の規模に関する基本的な情報を記述する。


[[tocN_03_02_04]]
===== 施設管理のための属性

施設管理のための属性は、港湾施設及び漁港施設、河川管理施設や公園管理施設等の施設管理に必要な情報を定義した属性である。施設管理のための属性は以下のデータ型を用いて記述する。


[[tocN_03_02_04_01]]
====== 施設分類属性（uro:FacilityTypeAttribute）

uro:FacilityTypeAttributeは、各分野で定める施設の区分を記述するためのデータ型である。CityGMLは、地物型を物体としての性質に着目して定義し、機能や用途は属性で区分している。例えば、「その他の構造物（con:OtherConstruction）」という地物型を定義し、uro:classにより「ダム」や「堤防」などを区分している。

これにより、都市に存在する様々な地物を、分野を問わず網羅的に、かつ、矛盾が無く表現することを目指している。一方、各分野には独自の施設の区分がある。この区分は当該分野での施設管理に必要な情報であるが、CityGMLの地物型の区分とは一致しない。そこで、これらの地物型に分野独自の区分を付与するためにこのデータ型を用いる。uro:FacilityTypeAttributeは、二つの属性をもつ。uro:classは分野を特定するための属性である。またuro:functionは、uro:classにより特定した分野における施設の区分を示す。

標準製品仕様書では、港湾施設、漁港施設及び公園施設については標準製品仕様書においてuro:functionの区分が示されている。その他の区分についてはuro:classへの分野の追加も含め、拡張製品仕様書において拡張できる。


[[tocN_03_02_04_02]]
====== 施設識別属性（uro:FacilityIdAttribute）

uro:FacilityIdAttributeは、施設の位置を特定する情報及び施設を識別する情報を記述するためのデータ型である。uro:FacilityIdAttributeは、施設を識別するための情報として、識別子（uro:id）や正式な名称以外の呼称（uro:alternativeName）に加え、施設の位置を示すための、都道府県（uro:prefecture）、市区町村（uro:city）及び開始位置の経緯度（uro:startLat、uro:startLong）を属性としてもつ。また、鉄道上や道路上の施設については、路線や距離標での位置特定のための属性（uro:route、uro:startPost、uro:endPost）を使用できる。

なお、河川管理施設の場合は、uro:FacilityIdAttributeを継承するuro:RiverFacilityIdAttributeを使用する。これにより、左右岸上での位置の情報を記述できる。


[[tocN_03_02_04_03]]
====== 施設詳細属性（uro:FacilityAttribute）

uro:FacilityAttributeは、各分野において施設管理に必要となる情報を記述するためのデータ型である。uro:FacilityAttributeは、抽象クラスであり、これを継承する具象となるデータ型に、施設の区分毎に必要となる情報を属性として定義している。

標準製品仕様書では、港湾施設、漁港施設及び公園施設について、細分した施設の区分ごとにデータ型を定義している。また、施設に関する工事や点検の状況や内容を記述するためのデータ型（uro:MaintenanceHistoryAttribute）を定義している。


[[tocN_03_02_05]]
===== 数値地形図属性（urc:DmAttribute）

公共測量標準図式に従った形状表現を行うために必要な属性である。 +
LOD0の幾何オブジェクトの他、数値地形図との互換性を保つために必要な情報が、属性として定義されている。


[[tocN_03_02_06]]
===== データ品質属性（urc:DataQualityAttribute）

その他の構造物オブジェクトの作成に使用した原典資料の記録や、適用した詳細なLODの区分を示すための属性である。

使用した原典資料やそれに基づくデータの品質、また、採用したLODは、データセットのメタデータに記録できる。ただし、データセット全体に対して一つのメタデータを作成することが基本となり、個々の都市オブジェクトの品質を記録することは困難である。

同じデータセットの中に、航空写真測量により作成したその他の構造物オブジェクトや完成図等から作成したその他の構造物オブジェクトというように、複数の品質をもつ都市オブジェクトが混在している場合には、都市オブジェクトごとにこの構造物品質属性を使用して、品質情報を記録することで、その品質を明確にできる。

そこで、標準製品仕様書では、個々のデータに対してデータ品質に関する情報を記述するための属性として、「データ品質属性」（urc:DataQualityAttribute）を定義している。データ品質属性は、属性としてデータ作成に使用した原典資料の地図情報レベル、その他原典資料の諸元及び精緻化したLODをもつ。

その他の構造物モデルは、外部LODのみを対象としているため、urc:ExteriorDataQualityAttributeを用いてデータ品質を記述する。3D都市モデルに含まれる全てのその他の構造物オブジェクトは、このデータ品質属性を必ず作成しなければならない。ただし、その他の構造物（con:OtherConstruction）に対してデータ品質属性を付与することはできるが、これを構成する屋根面や外壁面（con:AbstractConstructionSurfaceの下位クラス）にデータ品質属性を付与することはできない。


[[tocN_03_02_07]]
===== ADEで拡張された属性の記述

CityGML3.0では、地物型ごとに、属性を拡張するためのデータ型ADEOfXXX（XXXには地物型の名称が入る）が用意されている。また、拡張したデータ型を地物の属性として記述するための主題属性adeOfXXX（XXXには地物型の名称が入る）も用意されている。例えば、建築物（Building）という地物型に属性を追加したい場合、ADEOfBuildingを使う。このデータ型を継承して新しい属性を定義することで、主題属性adeOfBuildingの型として記述できるようになる。

ここで、その他の構造物の<<tocN_03_02_03,構造物構造属性>>、<<tocN_03_02_02,構造物管理属性>>、<<tocN_03_02_06,データ品質属性>>、<<tocN_03_02_05,数値地形図属性>>等の主題属性は、上述の仕組みを使って拡張して定義されたデータ型である。これらのデータ型を記述する場合には、拡張した地物型に対応する主題属性adeOfXXX（XXXには地物型の名称が入る）の型として記述しなければならない。

例えば、その他の構造物に特化した情報である、<<tocN_03_02_03,構造物構造属性>>はADEOfAbstractOtherConstructionを継承して定義されているため、adeOfOtherConstructionの型として記述する。また、<<tocN_03_02_02,構造物管理属性>>は、ADEOfAbstractConstructionを継承しているため、adeOfAbstractConstructionの型として記述する。さらに、<<tocN_03_02_06,データ品質属性>>は、ADEOfAbstractCityObjectを継承して定義されているため、adeOfAbstractCityObjectの型として記述する。

このように、ADEで拡張された属性が、どの地物型を拡張して定義されているかによって、主題属性として値を記述する場所が異なることに注意が必要である。

