[[tocI_03]]
=== luse:LandUse
luse:LandUseは土地利用を記述するための地物型である。


[[tocI_03_01]]
==== 土地利用の空間属性

標準製品仕様書では、土地利用モデルのLODは、LOD1のみを対象としている。


[[tocI_03_01_01]]
===== LOD1

luse:LandUseの空間属性は、LOD1において、高さをもたない面として表現する。

標準製品仕様書において、土地利用は都市計画基礎調査の土地利用現況を指すことから、土地利用の空間属性は、都市計画基礎調査の土地利用現況の面と一致する。


[[tocI_03_02]]
==== 土地利用の主題属性

土地利用の主題属性は、都市計画基礎調査の土地利用現況により得られた情報である。原典資料として、GISデータ（土地利用現況）又は調書（土地利用現況）を使用できる。また、作成したデータの品質に関する情報を格納するための属性（urc:DataQualityAttribute）がある。

[[tocI_03_02_01]]
===== 土地利用分類（luse:class）

土地利用の用途の区分を指す。土地利用分類の区分は、<<mlit_foundation_reqs,都市計画基礎調査実施要領（国土交通省都市局）>>による区分（<<tab-I-3>>）とする。属性classは、全国共通の土地利用の区分に基づき各土地利用にコードを割り振ることで、広域での集計や地域の比較を行うことを目的としている。各都市独自の土地利用の区分に基づく分類は、土地利用詳細属性（uro:LandUseDetailAttribute）を使用して記述する。

[[tab-I-3]]
.土地利用分類の区分
lutaml_gml_dictionary::../../sources/iur/codelists/4.0/Common_landUseType.xml[template="gml_dict_template.liquid",context=dict]


[[tocI_03_02_02]]
===== 土地利用詳細属性（uro:landUseDetailAttribute）

都市計画基礎調査の土地利用現況として記録された情報を格納するための属性である。属性の型であるuro:LandUseDetailAttributeには都市独自の土地利用の区分（uro:orgLandUse）の他、面積（uro:nominalArea）や建ぺい率（uro:buildingCoverageRate）など、様々な属性の箱が用意されている。都市計画基礎調査でこれらの情報が収集されている場合には、定義済みの属性を使用する。また、該当する属性が無い場合には、汎用属性を使用して拡張できる。

なお、都市独自の土地利用の区分（uro:orgLandUse）を作成する場合には、区分を示すコードリスト（LandUseDetailAttribute_orgLandUse.xml）を作成しなければならない。


[[tocI_03_02_03]]
===== データ品質属性（urc:DataQualityAttribute）

使用した原典資料やそれに基づくデータの品質、また、採用したLODは、データセットのメタデータに記録できる。ただし、データセット全体に対して一つのメタデータを作成することが基本となり、個々の都市オブジェクトの品質を記録することは困難である。

そこで、標準製品仕様書では、個々のデータに対してデータ品質に関する情報を記述するための属性として、「データ品質属性」（urc:DataQualityAttribute）を定義している。データ品質属性は、属性としてデータ作成に使用した原典資料の地図情報レベル、その他原典資料の諸元、精緻化したLOD等をもつ。3D都市モデルに含まれる全ての土地利用オブジェクトは、このデータ品質属性を必ず作成しなければならない。

[[tocI_03_02_04]]
===== ADEで拡張された属性の記述

CityGML3.0では、地物型ごとに、属性を拡張するためのデータ型ADEOfXXX（XXXには地物型の名称が入る）が用意されている。また、拡張したデータ型を地物の属性として記述するための主題属性adeOfXXX（XXXには地物型の名称が入る）も用意されている。例えば、建築物（Building）という地物型に属性を追加したい場合、ADEOfBuildingを使う。このデータ型を継承して新しい属性を定義することで、主題属性adeOfBuildingの型として記述できるようになる。

ここで、土地利用の<<tocI_03_02_02,土地利用詳細属性>>、<<tocI_03_02_03,データ品質属性>>等の主題属性は、上述の仕組みを使って拡張して定義されたデータ型である。これらのデータ型を記述する場合には、拡張した地物型に対応する主題属性adeOfXXX（XXXには地物型の名称が入る）の型として記述しなければならない。

例えば、土地利用に特化した情報である、<<tocI_03_02_02,土地利用詳細属性>>はADEOfLandUseを継承して定義されているため、adeOfLandUseの型として記述する。また、<<tocI_03_02_03,データ品質属性>>は、ADEOfAbstractCityObjectを継承して定義されているため、adeOfAbstractCityObjectの型として記述する。

このように、ADEで拡張された属性が、どの地物型を拡張して定義されているかによって、主題属性として値を記述する場所が異なることに注意が必要である。

