[[tocM_01]]
=== 概要

本附属書では、「3D都市モデル標準製品仕様書」（以下、「標準製品仕様書」という）に適合したデータ製品について、「トンネルモデル」に従って作成されるべき都市オブジェクト（以下、「トンネルオブジェクト」という）が満たすべき要件を示す。

標準製品仕様書が準拠するCityGML3.0では、従来の3D都市モデルのユースケースだけでなく、将来的に想定される多様なユースケースにも適用できるよう、データ構造の柔軟性が高められている。しかし、選択肢の増加は標準製品仕様の利用者に混乱をもたらす可能性がある。

そこで、本附属書では標準製品仕様書に準拠しつつ、実用性の高い選択肢を絞り込むことを目的とする。これにより、3D都市モデルの作成や利用ツールの開発の効率化に寄与する。

本付属書では、「3D都市モデル標準製品仕様書」（以下、「標準製品仕様書」という）に適合したデータ製品について、「トンネルモデル」に従って作成された都市オブジェクト（以下、「トンネルオブジェクト」という）が満たすべき要件と、妥当なトンネルモデルを作成するための標準的な作業手順を示す。


[requirements_class]
.妥当なトンネルオブジェクト
====
[%metadata]
identifier:: /req/tun
subject:: 妥当なトンネルオブジェクトの要件
description:: トンネルの説明とLODの要件
requirement:: /req/tun/1
requirement:: /req/tun/2
requirement:: /req/tun/3
requirement:: /req/tun/4
requirement:: /req/tun/5
requirement:: /req/tun/6
requirement:: /req/tun/7
requirement:: /req/tun/8
requirement:: /req/tun/9
requirement:: /req/tun/10
requirement:: /req/tun/11
requirement:: /req/tun/12
requirement:: /req/tun/13
requirement:: /req/tun/14
requirement:: /req/tun/15
requirement:: /req/tun/16
====
