[[tocE_03]]
=== tran:Railway

tran:Railwayは、鉄道の記述に使用する地物型である。


[[tocE_03_01]]
==== tran:Railwayの空間属性

tran:Railwayの空間属性は、いずれのLODにおいても、空となる。 +
tran:Railwayは、tran:TrafficSpace及びtran:AuxiliaryTrafficSpaceの集まりとなり、これらの部品となる地物が空間属性を持つ。

なお、標準製品仕様書では、鉄道の形状は、路面の表現に基づくことを基本とする。このとき、路面を表す面は、tran:Squareに含まれる、tran:TrafficSpace及びtran:AuxiliaryTrafficSpaceの境界面であり、tran:TrafficAreaとtran:AuxiliaryTrafficAreaの空間属性となる。

交通（鉄道）モデルにおいて、LOD0では鉄道の形状を線により表現し、LOD1以降は面として表現する。また、LOD2以降では、面に加えて線により表現する。LOD1では鉄道内の区分はできず、LOD2以降で鉄道内を区分可能となる。その座標はLOD0からLOD2までは高さをもたず、LOD3では高さをもつ。LOD0からLOD2では、交通（鉄道）オブジェクトを3次元の地形データに貼り付けることで3次元的に表示して利用することを想定している。

LOD0及びLOD1は、軌道中心線は都市計画基本図からの加工又は航空写真からの図化、鉄道用地は航空写真からの図化を前提とした区分である。LOD2は、鉄道事業者の保有資料（鉄道事業法施行規則第12条に定める、線路実測図である「平面図」及び「縦断面図」、又はこのデータ）からの取得を前提とした区分である。

鉄道は路線単位で作成し、鉄道の延長方向は以下の場所で区切る。


[requirement]
.交通（鉄道）オブジェクトの区切り位置
====
[%metadata]
identifier:: /req/rwy/2
subject:: 妥当な交通（鉄道）データセットの要件
description:: 交通（鉄道）オブジェクトは、以下に示す場所で区切る。
part:: 軌道が分岐又は合流する地点
part:: 鉄道構造の変化点（トンネル、橋梁）
part:: 市区町村界
part:: 位置正確度や取得方法が変わる場所
====


[[tocE_03_02]]
==== 鉄道の主題属性

鉄道の主題属性には、あらかじめCityGML又はGMLにおいて定義された属性（接頭辞tran、gml、core）と、i-URにより拡張された属性（接頭辞urc、uro）がある。CityGMLで定義された属性は、鉄道の名称や種類など、基本的な情報となる。i-URにより拡張された属性には、路線に関する情報を格納するための属性（uro:RailwayRouteAttribute）及び軌道中心線の線形情報を格納するための属性（uro:RailwayTrackAttribute）、数値地形図との互換性を保つための情報を格納するための属性（urc:DmAttribute）、さらに、作成したデータの品質に関する情報を格納するための属性（urc:DataQualityAttribute）がある。


[[tocE_03_02_01]]
===== データ品質属性（urc:DataQualityAttribute）

3D都市モデルでは、データ集合全体としての品質はメタデータに記録する。しかしながら、メタデータでは、個々のデータに対して位置正確度や適用したLOD等の品質を記述することが困難である。

そこで、標準製品仕様書では、個々のデータに対してデータ品質に関する情報を記述するための属性として、「データ品質属性」（urc:DataQualityAttribute）を定義している。データ品質属性は、属性としてデータ作成に使用した原典資料の地図情報レベル、その他原典資料の諸元及び精緻化したLODをもつ。

3D都市モデルに含まれる全ての交通（鉄道）オブジェクトは、このデータ品質属性を必ず作成しなければならない。ただし、鉄道（tran:Railway）に対してデータ品質属性を付与することはできるが、これを構成する交通領域（tran:TrafficArea）や交通補助領域（tran:AuxiliaryTrafficArea）にデータ品質属性を付与することはできない。


[[tocE_03_02_02]]
===== 数値地形図属性（urc:DmAttribute）

公共測量標準図式に従った形状表現に必要な情報を記述するための属性である。幾何オブジェクトのほか、数値地形図との互換性を保つために必要な情報が、属性として定義されている。 +
鉄道のレールによる表現を行いたい場合、「<<gsi_ops,付録７ 公共測量標準図式>>」（以下、「公共測量標準図式」という）に従う。これにより、従来の都市計画基本図の地図表現が可能となる。


[[tocE_03_02_03]]
===== ADEで拡張された属性の記述

// 付属書E内にRailwayRouteAttributeの記載なしのためリンク張れない。

CityGML3.0では、地物型ごとに、属性を拡張するためのデータ型ADEOfXXX（XXXには地物型の名称が入る）が用意されている。また、拡張したデータ型を地物の属性として記述するための主題属性adeOfXXX（XXXには地物型の名称が入る）も用意されている。例えば、建築物（Building）という地物型に属性を追加したい場合、ADEOfBuildingを使う。このデータ型を継承して新しい属性を定義することで、主題属性adeOfBuildingの型として記述できるようになる。

ここで、鉄道のRailwayRouteAttribute、<<tocE_03_02_01,データ品質属性>>、<<tocE_03_02_02,数値地形図属性>>等の主題属性は、上述の仕組みを使って拡張して定義されたデータ型である。これらのデータ型を記述する場合には、拡張した地物型に対応する主題属性adeOfXXX（XXXには地物型の名称が入る）の型として記述しなければならない。

例えば、鉄道に特化した情報である、RailwayRouteAttributeはADEOfRailwayを継承して定義されているため、adeOfRailwayの型として記述する。また、<<tocE_03_02_01,データ品質属性>>は、ADEOfAbstractCityObjectを継承して定義されているため、adeOfAbstractCityObjectの型として記述する。

このように、ADEで拡張された属性が、どの地物型を拡張して定義されているかによって、主題属性として値を記述する場所が異なることに注意が必要である。

