[[tocE_04]]
=== tran:TrafficArea及びtran:AuxiliaryTrafficArea

交通（鉄道）モデルと同様に、鉄道の形状は、tran:Railwayに含まれる、tran:TrafficSpace及びtran:AuxiliaryTrafficSpaceの境界面であるtran:TrafficArea及びtran:AuxiliaryTrafficAreaの空間属性により表現することを基本とする。


[[tocE_04_01]]
==== tran:TrafficArea及びtran:AuxiliaryTrafficAreaの空間属性


[[tocE_04_01_01]]
===== LOD0

tran:TrafficArea及びtran:AuxiliaryTrafficAreaの空間属性は、LOD0において、ネットワークを表す線（core:lod0MultiCurve）とする。 +
このとき、交通（鉄道）オブジェクトは、交通（鉄道）モデル（LOD0）の定義に従ったものでなければならない。


[requirement]
.鉄道のLOD0形状定義
====
[%metadata]
identifier:: /req/rwy/3
subject:: 妥当な交通（鉄道）データセットの要件
description:: 鉄道のLOD0の形状は、交通（鉄道）モデル（LOD0）の定義に従う。
====

LOD0は鉄道を線として表現するが、このときの線は、ネットワーク（鉄道中心線又は軌道中心線）のいずれかを選択できる。 +
「<<gsi_ops,付録７ 公共測量標準図式>>」（以下、「公共測量標準図式」という）に従い、レールで取得したい場合は、<<tocE_03_02_01>>を使用する。


[[tocE_04_01_02]]
===== LOD1

tran:TrafficArea及びtran:AuxiliaryTrafficAreaの空間属性は、LOD1において、多曲面（core:lod1MultiSurface）とする。 +
このとき、交通（鉄道）オブジェクトは、交通（鉄道）モデル（LOD1）の定義に従ったものでなければならない。


[requirement]
.鉄道のLOD1形状定義
====
[%metadata]
identifier:: /req/rwy/4
subject:: 妥当な交通（鉄道）データセットの要件
description:: 鉄道のLOD1の形状は、交通（鉄道）モデル（LOD1）の定義に従う。
====


[[tocE_04_01_03]]
===== LOD2

tran:TrafficArea及びtran:AuxiliaryTrafficAreaの空間属性は、LOD2において、多曲面（core:lod2MultiSurface）とする。 +
このとき、交通（鉄道）オブジェクトは、交通（鉄道）モデル（LOD2）の定義に従ったものでなければならない。


[requirement]
.鉄道のLOD2形状定義
====
[%metadata]
identifier:: /req/rwy/5
subject:: 妥当な交通（鉄道）データセットの要件
description:: 鉄道のLOD2の形状は、交通（鉄道）モデル（LOD2）の定義に従う。
====


[[tocE_04_01_04]]
===== LOD3

tran:TrafficArea及びtran:AuxiliaryTrafficAreaの空間属性は、LOD3において、多曲面（core:lod3MultiSurface）とする。 +
このとき、交通（鉄道）オブジェクトは、交通（鉄道）モデル（LOD3）の定義に従ったものでなければならない。


[requirement]
.鉄道のLOD3形状定義
====
[%metadata]
identifier:: /req/rwy/6
subject:: 妥当な交通（鉄道）データセットの要件
description:: 鉄道のLOD3の形状は、交通（鉄道）モデル（LOD3）の定義に従う。
====


