[[toc6_03]]
=== メタデータの作成

メタデータとは、データ（ここでは、「((3D都市モデル))」）を説明するための情報である。((3D都市モデル))のメタデータとして、以下の四種類を作成する。それぞれ作成手順や内容を示す。

* JMP2.0形式のメタデータ（<<toc6_03_02>>）
* md形式のREADME（<<toc6_03_03>>）
* 原典資料リスト（<<toc6_03_04>>）
* 索引図（<<toc6_03_05>>）


[[toc6_03_01]]
==== メタデータの作成単位

((3D都市モデル))のメタデータは、((CityGML))形式で作成する全てのデータを一式として作成する。メタデータは、拡張製品仕様書に従った3D都市モデルと、((3D都市モデル))((オープンデータ))のそれぞれについて作成する。

メタデータ作成における留意点を以下に示す。

[requirement]
.拡張地物のメタデータ一括作成
====
[%metadata]
identifier:: /att/deliverable/1
subject:: 標準作業手順
class:: 留意事項
statement:: 拡張製品仕様書に、地物型を追加した場合は、建築物や道路等とまとめて一式としてメタデータを作成してよい。
====

[requirement]
.3D都市モデルのメタデータ分割ルール
====
[%metadata]
identifier:: /att/deliverable/2
subject:: 標準作業手順
class:: 留意事項
[statement]
--
3D都市モデルの管理上必要な場合にはメタデータを分ける。 +
メタデータは、3D都市モデル全体について、一つのメタデータを作成することを原則とする。 +
ただし、以下の場合には3D都市モデル全体のメタデータとは別に、対象を限定したメタデータを作成する。

* 原典資料の管理者が3D都市モデルの整備主体とは異なる場合（ただし、原典資料がオープンデータである場合は除く。）
** 洪水浸水想定区域、津波浸水想定、高潮浸水想定区域、内水浸水想定区域及び土砂災害警戒区域にかかる原典資料として、<<nlftp,国土数値情報（オープンデータ）>>ではなく、河川管理者等から貸与されたデータを使用した場合は、それぞれメタデータを作成する。
** 建築物モデル（LOD4）の原典資料として、整備主体以外の施設管理者から貸与されたBIMモデル等を使用した場合は、建築物モデル（LOD4）に対するメタデータを作成する。
* モデル整備事業者が対象地物によって異なる場合
** モデル整備事業者毎に作成する。
* 空間参照系が日本測地系2011における経緯度座標系と東京湾平均海面を基準とする標高の複合座標参照系以外の場合
** 地下埋設物モデルは空間参照系が日本測地系2011における平面直角座標系と東京湾平均海面を基本とする標高の複合座標参照系であるため、地下埋設物モデルに対するメタデータを作成する。
* 3D都市モデルの一部を更新する場合
** 更新した地物型についてのメタデータを作成する。複数の地物型を更新した場合、その他のメタデータを分割するルールに該当しない場合には、一つのメタデータにまとめてよい。

--
====

[requirement]
.3D都市モデル関連データのメタデータ作成ルール
====
[%metadata]
identifier:: /att/deliverable/3
subject:: 標準作業手順
class:: 留意事項
[statement]
--
3D都市モデルとは別に、関連するデータを納める場合には、それぞれにメタデータを作成する。

* 3D都市モデルとして作成した地形にドレープするための航空写真や衛星画像等の画像を成果品として納める場合には、画像用のメタデータを作成する。
* 3D都市モデルから変換したデータ（例：OBJ形式）を成果品として納める場合には、これのためのメタデータを作成する。このとき、3D都市モデルから変換したデータであることを明記すること。

--
====

[[toc6_03_02]]
==== JMP2.0形式メタデータの作成手順

((3D都市モデル))を説明するための情報として、メタデータを作成する。メタデータの仕様は、国土地理院が定めた「JMP2.0」を使用する。JMP2.0は、JPGISに準拠したメタデータ記述形式である。

メタデータの作成には、国土地理院が提供するメタデータエディタを使用する。

* 【手順】
* 手順1．メタデータエディタをインストールする。
** https://www.gsi.go.jp/gijyutukanri/gijyutukanri41027.html より入手可能

* 手順2．メタデータエディタの詳細入力モードを使用し、各項目を入力する。
** 入力する必須項目を<<tab-6-1>>に示す。
** 一部更新を行う場合は、<<tocW>>を参照すること。
+
--
[[tab-6-1]]
include::../../../common/sections/com_Metadata_Item.adoc[]
--

* 手順3．メタデータエディタを用いてJMP2.0形式にて出力する。
** ファイル名称は、<<toc6_04_04>>に従う。

[NOTE,type=commentary]
--
<<tab-6-1>>に示す項目は、3D都市モデルの利用者がメタデータにより3D都市モデルの概要を得ようとした場合に、利用者が想定したユースケースに適合したデータであるか否かを判断する重要な情報である。そのため、必須項目とする。

メタデータは、3D都市モデルを再利用する場合に、3D都市モデルの概要を把握するために必要な情報である。メタデータを充実させることでより価値の高いデータ製品となり、様々な人に使ってもらえるようになる。そのため、必須としない項目についても、可能な限り記述することが望ましい。
--

[[toc6_03_03]]
==== READMEファイルの作成手順

データ製品の概要書として、READMEを作成する。

===== READMEの仕様
(((3D都市モデル)))(((建築物)))(((標準製品仕様書)))(((都市計画決定情報)))

. 作成単位
** データ製品に対して一つのREADMEファイルを作成する。
. ファイルフォーマット
** md（マークダウン）形式とする。ファイル拡張子は、.mdとする。
. ファイル名称
** README（拡張子を含めると、README.md）
. 記載項目
** READMEに含むべき項目は<<tab-6-2>>のとおりとする。

[[tab-6-2]]
include::../../../common/sections/com_Metadata_Readme.adoc[]


===== 作成手順

* 【手順】
* 手順1．テキストエディタ―等を使用し、READMEファイルに入力する。
** 3D都市モデル拡張製品仕様書テンプレートセットの、README.md（テンプレート）を使用する。
*** 3D都市モデル拡張製品仕様書テンプレートセットは、以下のURLよりダウンロードできる。 +
https://www.mlit.go.jp/plateaudocument/[]


[[toc6_03_04]]
==== 原典資料リストの作成手順

JMP2.0は、データ製品を作成する際に使用した原典資料の諸元を詳細に記述できないことから、((標準製品仕様書))では、原典資料リストのための仕様を定めている。((3D都市モデル))を作成する際には、必ずこの原典資料リストを作成しなければならない。

===== 原典資料リストの仕様
(((3D都市モデル)))(((LOD0)))(((テクスチャ)))

. 作成単位
** データ製品に対して一つの原典資料リストを作成することを基本とする。
** ただし、行政界を跨ぐ都市オブジェクトを、隣接する市区町村の3D都市モデルから取得し、これを当該市区町村の3D都市モデルに重複して含めた場合、隣接する市区町村の3D都市モデルから取得した都市オブジェクトの原典資料リストは分けることができる。
. ファイルフォーマット
** CSV形式とする。拡張子は、「.csv」とする。
. ファイル名称
** ``udx\_[都市コード]_[整備年度]_resource``
// ** ``udx_[都市コード]_[整備年度]_resource``
** ``[都市コード]``は、成果品のルートフォルダの名称に含める``[都市コード]``とする。
** 隣接する市区町村の3D都市モデルから取得した都市オブジェクトの原典資料リストの名称に使用する``[都市コード]``は、隣接する市区町村の都市コードとする。
. 記載項目

include::../../../common/sections/com_Metadata_Material.adoc[]

===== 作成手順

* 【手順】
* 手順1．表管理ソフト等を使用し、原典資料リストのリストを作成する。
** 製品仕様書作成用テンプレートセットの、原典資料リストテンプレートを使用する。
*** 製品仕様書作成用テンプレートは、以下のURLよりダウンロードできる +
https://www.mlit.go.jp/plateaudocument/[]

* 手順2．以下に示すCSVファイルの仕様に従い、CSVファイルフォーマットで保存する。
** 記載項目の組を1レコードとし、以下に示す規則に従い出力する。
** CSVファイル仕様
+
--
include::../../../common/sections/com_Metadata_Material_File.adoc[]
--

[requirement]
.異なる原典資料の地物属性は行を分ける
====
[%metadata]
identifier:: /att/deliverable/4
subject:: 標準作業手順
class:: 留意事項
[statement]
--
同一メッシュ内の同じ地物の同じ属性に対して異なる原典資料が使用されている場合は、行を分ける。 +
あるメッシュに含まれる建築物のLOD1が、都市計画基本図のDMデータから作成した場合と、都市計画基礎調査のGISデータから作成した場合と混在していた場合、行を分ける。
--
====

[requirement]
.複数値の列挙は、他項目が同一の場合のみ
====
[%metadata]
identifier:: /att/deliverable/5
subject:: 標準作業手順
class:: 留意事項
[statement]
--
一つの項目内で複数の値を列挙する場合は、その他の項目の値が同一である場合に限る。 +
例えば、<<nlftp,国土数値情報>>のように、1つの原典資料であるが、複数の地図情報レベルが混在している場合がある。この場合は、地図情報レベルを;（セミコロン）により区切り、複数の地図情報レベルを列挙することができる。 +
ただし、一つの項目内で複数の値を列挙する場合は、その他の項目（作成日、座標参照系等）は同一でなければならない。
--
====

[[toc6_03_05]]
==== 索引図

索引図は、3D都市モデルの空間範囲を、LOD別に地図上で示す。

===== 索引図の仕様
(((3D都市モデル)))

. 索引図のタイトルは、「〇〇3D都市モデル整備範囲図」（〇〇の部分は整備範囲となる市区町村名又は都道府県名を記載）とする。
. 3D都市モデルの詳細度（LOD1～4）ごとに色を分けて表示する。 +
LOD3及びLOD4の整備範囲は、整備範囲の広さに応じて詳細図を表示する。
. 対象範囲の標準地域メッシュ（２次メッシュ、３次メッシュ）のメッシュとメッシュ番号を表示する。
. 凡例を表示する。主な項目は次の通りとする。
.. 2次メッシュ及びそのメッシュ数：記号は水色（R:5,G:110,B:255）の太線の四角を標準とする。
.. 3次メッシュ及びそのメッシュ数：記号は黒色（R:0,G:0,B:0）の中太線の四角を標準とする。
.. LOD1整備範囲（範囲の通称）及び面積km2：記号は黒色（R:0,G:0,B:0）の太線の四角を標準とする。
.. LOD2整備範囲（範囲の通称）及び面積km2：記号は赤色（R:240,G:5,B:0）の太線の四角を標準とする。
.. LOD3整備範囲（範囲の通称）及び数量（km2又はkm等）：記号は緑色（R:90,G:255,B:0）の太線の四角又は線を標準とする。
.. LOD4整備範囲（範囲の通称）及び数量（km2又はkm等）：記号は青色（R:0,G:0,B:255）の太線の四角又は線を標準とする。
+
面積及び数量は、README.mdに記載する整備面積及び棟数・箇所数に一致する。

. 背景地図は、国土地理院の地理院地図（地理院タイル）を標準とする。
. 縮尺は任意とし用紙サイズA4を基本とする。レイアウトは対象範囲の形状を考慮し縦又は横いずれも可とする。
. ファイル形式はPDFとする。

===== 作成手順

* 【手順】
* 手順1．GISやCAD等で図を作成し、画像形式にしたものをテンプレート（WORD形式）に張り付ける。
** 製品仕様書作成用テンプレートセットに含まれる、索引図テンプレートを使用することを基本とする。
*** 製品仕様書作成用テンプレートは、以下のURLよりダウンロードできる +
https://www.mlit.go.jp/plateaudocument/[]
** 使用するGISやCADの出力機能を用いて、索引図の仕様1から7に示す仕様に従った索引図を出力してもよい。
* 手順2．PDF形式に変換する。