[[tocS_03]]
=== dem:ReliefFeature


[[tocS_03_01]]
==== 地形の空間属性

dem:ReliefFeatureは、地形要素（dem:AbstractReliefComponent）の集まりとして表現される。 +
dem:ReliefFeature自身は空間属性をもたず、空間属性は、部品となる地形要素のみがもつ。


[[tocS_03_01_01]]
===== LOD0

地形モデル（LOD0）では、地形の形状を、等高線（dem:BreaklineRelief）、標高点（dem:MassPointRelief）又は標高グリッド（dem:RasterRelief）として表現する。 +
このとき、地形オブジェクトは、地形モデル（LOD0）の定義に従ったものでなければならない。このとき、地形オブジェクトは、地形モデル（LOD0）の定義に従ったものでなければならない。

なお、公共測量標準図式に従った表現を行いたい場合は、数値地形図属性（urc:DmAttribute）を使用する。


[requirement]
.地形のLOD0形状定義
====
[%metadata]
identifier:: /req/dem/2
subject:: 妥当な地形データセットの要件
description:: 地形のLOD0の形状は、地形モデル（LOD0）の定義に従う。
====


[[tocS_03_01_02]]
===== LOD1

地形モデル（LOD1）では、地形の形状を、不規則三角網（dem:TINRelief）、標高点（dem:MassPointRelief）又は標高グリッド（dem:RasterRelief）として表現する。 +
このとき、地形オブジェクトは、地形モデル（LOD1）の定義に従ったものでなければならない。


[requirement]
.地形のLOD1形状定義
====
[%metadata]
identifier:: /req/dem/3
subject:: 妥当な地形データセットの要件
description:: 地形のLOD1の形状は、地形モデル（LOD1）の定義に従う。
====


[[tocS_03_01_03]]
===== LOD2

地形モデル（LOD2）では、地形の形状を、不規則三角網（dem:TINRelief）、標高点（dem:MassPointRelief）又は標高グリッド（dem:RasterRelief）として表現する。 +
このとき、地形オブジェクトは、地形モデル（LOD2）の定義に従ったものでなければならない。


[requirement]
.地形のLOD2形状定義
====
[%metadata]
identifier:: /req/dem/4
subject:: 妥当な地形データセットの要件
description:: 地形のLOD2の形状は、地形モデル（LOD2）の定義に従う。
====


[[tocS_03_01_04]]
===== LOD3

地形モデル（LOD3）では、地形の形状を、不規則三角網（dem:TINRelief）、標高点（dem:MassPointRelief）又は標高グリッド（dem:RasterRelief）として表現する。 +
このとき、地形オブジェクトは、地形モデル（LOD3）の定義に従ったものでなければならない。


[requirement]
.地形のLOD3形状定義
====
[%metadata]
identifier:: /req/dem/5
subject:: 妥当な地形データセットの要件
description:: 地形のLOD3の形状は、地形モデル（LOD3）の定義に従う。
====


[[tocS_03_02]]
==== 地形の主題属性

地形の主題属性には、あらかじめCityGML又はGMLにおいて定義された属性（接頭辞dem、core、gml）がある。また、標準製品仕様書では、i-URにおいて拡張された作成したデータの品質に関する情報を格納するための属性（urc:DataQualityAttribute）や公共測量標準図式に従った表現に必要となる属性（urc:DmAttribute）がある。


[[tocS_03_02_01]]
===== データ品質属性（urc:DataQualityAttribute）

使用した原典資料やそれに基づくデータの品質、また、採用したLODは、データセットのメタデータに記録できる。ただし、データセット全体に対して一つのメタデータを作成することが基本となり、個々の都市オブジェクトの品質を記録することは困難である。

そこで、標準製品仕様書では、個々のデータに対してデータ品質に関する情報を記述するための属性として、「データ品質属性」（urc:DataQualityAttribute）を定義している。データ品質属性は、属性としてデータ作成に使用した原典資料の地図情報レベル、その他原典資料の諸元及び精緻化したLODをもつ。

3D都市モデルに含まれる全ての地形オブジェクトは、このデータ品質属性を必ず作成しなければならない。


[[tocS_03_02_02]]
===== 数値地形図属性（urc:DmAttribute）

公共測量標準図式に従った形状表現に必要な情報を記述するための属性である。幾何オブジェクトのほか、数値地形図との互換性を保つために必要な情報が、属性として定義されている。


[[tocS_03_02_03]]
===== ADEで拡張された属性の記述

// 数値地形図属性についての記述はなくてもよい？追記するならリンク可能

CityGML3.0では、地物型ごとに、属性を拡張するためのデータ型ADEOfXXX（XXXには地物型の名称が入る）が用意されている。また、拡張したデータ型を地物の属性として記述するための主題属性adeOfXXX（XXXには地物型の名称が入る）も用意されている。例えば、建築物（Building）という地物型に属性を追加したい場合、ADEOfBuildingを使う。このデータ型を継承して新しい属性を定義することで、主題属性adeOfBuildingの型として記述できるようになる。

ここで、地形の<<tocS_03_02_01,データ品質属性>>は、上述の仕組みを使って拡張して定義されたデータ型である。これらのデータ型を記述する場合には、拡張した地物型に対応する主題属性adeOfXXX（XXXには地物型の名称が入る）の型として記述しなければならない。

例えば、<<tocS_03_02_01,データ品質属性>>はADEOfAbstractCityObjectを継承して定義されているため、adeOfAbstractCityObjectの型として記述する。

このように、ADEで拡張された属性が、どの地物型を拡張して定義されているかによって、主題属性として値を記述する場所が異なることに注意が必要である。

