[[tocP_03]]
=== uro:UtilityNetworkElement

uro:UtilityNetworkElementは、地下埋設物の記述に使用する地物型である。 +
ただし、uro:UtilityNetworkElementは抽象地物であり、実装においては、この下位型の具象となる地物型を使用する。

下位型の地物型には、以下がある。

* uro:UtilityLink
* uro:UtilityNode
* uro:UtilityNodeContainer

これらの下位型も抽象地物であり、さらにこれを特化した具象となる地物型がそれぞれ定義されている。 +
例えば、uro:UtilityLinkを継承する地物型には、ケーブル（uro:Cable）、管路（uro:Pipe）及びダクト（uro:Duct）がある。


[[tocP_03_01]]
==== 地下埋設物の空間属性

uro:UtilityNetworkElementの空間属性には、LOD0からLOD3までの4つがある。これらは、いずれも地下埋設物の外部の形状を表す。


[[tocP_03_01_01]]
===== LOD0

uro:UtilityNetworkElementの空間属性は、LOD0において、点（core:lod0Point）、線（core:lod0MultiCurve）又は面（core:lod0MultiSurface）により表現する。 +
このとき、地下埋設物オブジェクトは、地下埋設物モデル（LOD0）の定義に従ったものでなければならない。


[requirement]
.地下埋設物のLOD0形状定義
====
[%metadata]
identifier:: /req/unf/2
subject:: 妥当な地下埋設物データセットの要件
description:: 地下埋設物のLOD0の形状は、地下埋設物モデル（LOD0）の定義に従う。
====

地下埋設物モデル（LOD0）は、地下埋設物のGISデータやCADデータをCityGML形式に変換し、3D都市モデル上に重畳して使用することを想定したデータである。


[[tocP_03_01_02]]
===== LOD1

uro:UtilityNetworkElementの空間属性は、LOD1において、立体（core:lod1Solid）により表現する。 +
このとき、地下埋設物オブジェクトは、地下埋設物モデル（LOD1）の定義に従ったものでなければならない。


[requirement]
.地下埋設物のLOD1形状定義
====
[%metadata]
identifier:: /req/unf/3
subject:: 妥当な地下埋設物データセットの要件
description:: 地下埋設物のLOD1の形状は、地下埋設物モデル（LOD1）の定義に従う。
====

地下埋設物モデル（LOD1）では、マンホール及びハンドホールは、外周の正射影として、蓋の上からの正射影を包含する矩形を取得する。また、管路は外径が不明な場合には内径及び管種から外径を推定し、この外径を使用して外周の正射影を推定する（<<tocP_08_02_06>>参照）。

地下埋設物モデル（LOD1）では、地下埋設物の形状を地表から一律の深さで立ち上げた立体として表現するため、地下埋設物の正確な深さは分からないが、埋設物が存在する可能性がある空間を表現できる。


[[tocP_03_01_03]]
===== LOD2

uro:UtilityNetworkElementの空間属性は、LOD2において、立体（core:lod2Solid）又は多曲面（core:lod2MultiSurface）により表現する。

地下埋設物モデル（LOD2）は、LOD2.0、LOD2.1及びLOD2.2に細分される。 +
このとき、地下埋設物オブジェクトは、地下埋設物モデル（LOD2）の定義に従ったものでなければならない。

LOD2.0は、地下埋設物の形状を立体として表現する。立体は、地下埋設物の外周の正射影を取得し、埋設物が埋まった深さから一律の高さで下向きに立ち上げて作成する。一律の高さは、地下埋設物の径とする。また、複数の地下埋設物がまとまって埋設されている場合は、最外縁の正射影を取得し、埋設物が埋まった最上部から埋設物の最下端まで、一律の高さで下向きに立ち上げる。 +
LOD2.1は、地下埋設物の形状を多曲面として表現する。多曲面は、地下埋設物の外形を構成する面であり、曲面の場合は、データセットが採用する地図情報レベルの水平及び高さの誤差の標準偏差に収まるよう平面に分割される。面を構成する各頂点には埋設物の高さを与える。地下埋設物モデル（LOD2.0）までとは異なり、まとまって埋設されている地下埋設物も、個々に表現される。 +
LOD2.2は、地下埋設物の形状を多曲面として表現する。多曲面は、地下埋設物の外形を構成する面であり、曲面の場合は、データセットが採用する地図情報レベルの水平及び高さの誤差の標準偏差に収まるよう平面に分割される。面を構成する各頂点には埋設物の高さを与える。地下埋設物モデル（LOD2.0）までとは異なり、まとまって埋設されている地下埋設物も、個々に表現される。


[requirement]
.地下埋設物のLOD2形状定義
====
[%metadata]
identifier:: /req/unf/4
subject:: 妥当な地下埋設物データセットの要件
description:: 地下埋設物のLOD2の形状は、地下埋設物モデル（LOD2）の定義に従う。
====

地下埋設物の外周の正射影は、地下埋設物の中心位置（LOD0）と地下埋設物の種類及び内径により定まる外径を用いて推定した外周で代替できる。

地下埋設物モデル（LOD2）では、地下埋設物が埋まった最も浅い位置から深い位置まで一律の高さで下向きに立ち上げた立体となるため、地下埋設物の位置をある程度正確に把握することが可能となる。


[[tocP_03_01_04]]
===== LOD3

uro:UtilityNetworkElementの空間属性は、LOD3において、多曲面（core:lod3MultiSurface）により表現する。 +
このとき、地下埋設物オブジェクトは、地下埋設物モデル（LOD3）の定義に従ったものでなければならない。


[requirement]
.地下埋設物のLOD3形状定義
====
[%metadata]
identifier:: /req/unf/5
subject:: 妥当な地下埋設物データセットの要件
description:: 地下埋設物のLOD3の形状は、地下埋設物モデル（LOD3）の定義に従う。
====

