[[tocC_07]]
=== bldg:BuildingRoom

bldg:BuildingRoomは、部屋を記述するために使用する地物型である。bldg:BuildingRoomは、建築物の内部空間の表現に使用する。すなわち、bldg:BuildingRoomが出現するのは、建築物モデルにおける内部LODのみである。

bldg:BuildingRoomは、bldg:Building又はbldg:BuildingPartに含まれる地物として記述する。 +
このとき、bldg:BuildingRoomは、複数の地物の集まりとして表現することができる。bldg:BuildingRoomに含むことができる地物とは、以下である。

* 部屋を区切る境界面（con:AbstractConstructionSurfaceの下位型）
* 部屋に付属する固定的な設備（bldg:BuildingInstallation）
* 部屋の中に設置された移動可能な家具（bldg:BuildingFurniture）


[[tocC_07_01]]
==== 部屋の空間属性


[[tocC_07_01_01]]
===== LOD0

bldg:BuildingRoomは多曲面（core:lod0MultiSurface）又は線（core:lod0MultiCurve）として表現する。ただし、原則として多曲面を使用する。

このとき、面の境界となる線は、天井面（con:CeilingSurface）、床面（con:FloorSurface）、内壁面（con:InteriorWallSurface）、閉鎖面（core:ClosureSurface）、扉面（con:DoorSurface）又は窓面（con:WindowSurface）のいずれかとして表現することができる。


[[tocC_07_01_02]]
===== LOD1

bldg:BuildingRoomは立体（core:lod1Solid）として表現する。

このとき、立体の境界面は、天井面（con:CeilingSurface）、床面（con:FloorSurface）、内壁面（con:InteriorWallSurface）、閉鎖面（core:ClosureSurface）、扉面（con:DoorSurface）又は窓面（con:WindowSurface）のいずれかとして表現することができる。


[[tocC_07_01_03]]
===== LOD2

bldg:BuildingRoomは立体（core:lod2Solid）又は多曲面（core:lod2MultiSurface）として表現する。ただし、原則として立体を使用する。

このとき、立体の境界面又は多曲面を構成する面は、天井面（con:CeilingSurface）、床面（con:FloorSurface）、内壁面（con:InteriorWallSurface）、閉鎖面（core:ClosureSurface）、扉面（con:DoorSurface）又は窓面（con:WindowSurface）のいずれかとして表現することができる。


[[tocC_07_01_04]]
===== LOD3

bldg:BuildingRoomは立体（core:lod3Solid）又は多曲面（core:lod3MultiSurface）として表現する。

このとき、立体の境界面又は多曲面を構成する面は、天井面（con:CeilingSurface）、床面（con:FloorSurface）、内壁面（con:InteriorWallSurface）、閉鎖面（core:ClosureSurface）、扉面（con:DoorSurface）又は窓面（con:WindowSurface）のいずれかとして表現することができる。


[[tocC_07_02]]
==== 部屋の主題属性

bldg:BuildingRoomは、建築物の内部の部屋の総称となる。そのため、部屋の機能や用途は、主題属性bldg:class及びbldg:functionにより区分する。


[requirement]
.bldg:BuildingRoomの機能区分方法
====
[%metadata]
identifier:: /req/bldg/23
subject:: 妥当な建築物データセットの要件
description:: bldg:BuildingRoomは、bldg:class及びbldg:functionによりその機能や用途を区分する。
====

bldg:class及びbldg:functionが取りうる値は、コードリストにより定義されている。標準製品仕様書では、bldg:class及びbldg:functionの定義域として建築生産で必要とする建築部位、工法及び設備などの名称を体系的に整理したUniclass2015のうち、Space/Locationのカテゴリを採用している。これは、建築物モデル・内部（LOD3）は、BIMモデルからの変換によるデータ作成が進むと想定され、bldg:BuildingRoomに対応するIFCのクラスとして、IfcSpaceが存在するからである。

