[[tocH_03]]
=== tran:Waterway

tran:Waterwayは、航路の記述に使用する地物型である。


[[tocH_03_01]]
==== tran:Waterwayの空間属性

tran:Waterwayの空間属性は、空となる。 +
tran:Waterwayは、tran:TrafficSpaceの集まりとなり、これの部品となる地物が空間属性を持つ。

なお、標準製品仕様書では、航路の形状は、多曲面を基本とする。このとき、多曲面は、tran:Waterwayに含まれる、tran:TrafficSpaceの境界面であり、tran:TrafficAreaの空間属性となる。


[[tocH_03_01_01]]
===== 航路の連続性の表現

連続する交通（航路）オブジェクトは、その境界が一致しなければならない。


[requirement]
.tran:Waterwayの幾何座標一致条件
====
[%metadata]
identifier:: /req/wwy/2
subject:: 妥当な交通（航路）データセットの要件
description:: 連続するtran:Waterwayに含まれる幾何オブジェクトは、同一のLODにおいて、その境界の座標を一致させなければならない。
====

[[tocH_03_01_02]]
===== LOD1における交通（航路）オブジェクトの区切り位置

交通（航路）モデル（LOD1）では、航路の形状を面として表現する。このとき、面の境界は法令により指定された航路の区域の境界となる。交通（航路）オブジェクトは、他の航路と交わる部分で区切る。


[requirement]
.tran:Waterwayの幾何座標一致条件
====
[%metadata]
identifier:: /req/wwy/3
subject:: 妥当な交通（航路）データセットの要件
description:: tran:Waterwayのオブジェクトは、以下に示す場所で区切る。
part:: 二つ以上の航路が交わる部分
====


[[tocH_03_02]]
==== 航路の主題属性

tran:Waterwayの主題属性には、tran:Waterwayに定義された属性と、これが継承するtran:AbstractTransportationSpaceに定義された属性がある。

なお、tran:Waterwayが継承するurc:DmAttributeは、数値地形図との互換性を保つための情報を格納するための属性であり、航路は数値地形図では表現されないことから、標準製品仕様書では使用しない。


[[tocH_03_02_01]]
===== 航路詳細属性（uro:waterweyDetailAttribute）

航路の詳細な属性として、航路の管理番号、進行方向、幅員、延長、航法、計画水深、速力制限、対象船型を定義する。

幅員が幅をもって指定されている場合は、最小値（uro:minimumWidth）及び最大値（uro:maximumWidth）の両方を入力する。特定の値が指定されている場合は、最小値（uro:minimumWidth）のみを入力する。


[[tocH_03_02_02]]
===== データ品質属性（urc:DataQualityAttribute）

航路のデータ作成に使用した原典資料を記述するための属性である。3D都市モデルでは、データ集合全体としての品質はメタデータに記録する。しかしながら、メタデータでは、個々のデータに対して位置正確度や適用したLOD等の品質を記述することが困難である。

そこで、標準製品仕様書では、個々のデータに対してデータ品質に関する情報を記述するための属性として、「データ品質属性」（urc:DataQualityAttribute）を定義している。データ品質属性は、属性としてデータ作成に使用した原典資料の地図情報レベル、その他原典資料の諸元及び精緻化したLODをもつ。

3D都市モデルに含まれる全ての交通（航路）モデルは、このデータ品質属性を必ず作成しなければならない。ただし、航路（tran:Waterway）に対してデータ品質属性を付与することはできるが、これを構成する交通領域（tran:TrafficArea）や交通補助領域（tran:AuxiliaryTrafficArea）にデータ品質属性を付与することはできない。


[[tocH_03_02_03]]
===== 施設管理のための属性

施設管理のための属性は、港湾施設及び漁港施設、河川管理施設や公園管理施設等の施設管理に必要な情報を定義した属性である。施設管理のための属性は以下のデータ型を用いて記述する。


[[tocH_03_02_03_01]]
====== 施設分類属性（uro:FacilityTypeAttribute）

uro:FacilityTypeAttributeは、各分野で定める施設の区分を記述するためのデータ型である。 +
CityGMLは、地物型を物体としての性質に着目して定義し、機能や用途は属性で区分している。 +
これにより、都市に存在する様々な地物を、分野を問わず、網羅的に、かつ、矛盾が無く表現することを目指している。

一方、各分野には独自の施設の区分がある。この区分は当該分野での施設管理に必要な情報であるが、CityGMLの地物型の区分とは一致しない。

そこで、これらの地物型に分野独自の区分を付与するためにこのデータ型を用いる。 +
uro:FacilityTypeAttributeは、二つの属性をもつ。uro:classは分野を特定するための属性である。またuro:functionは、uro:classにより特定した分野における施設の区分を示す。

標準製品仕様書では、港湾施設管理、漁港施設管理及び公園施設管理のそれぞれの分野についてはuro:functionの区分を示している。その他の分野における区分が必要となる場合はuro:classへの分野の追加も含め、拡張製品仕様書において追加できる。


[[tocH_03_02_03_02]]
====== 施設識別属性（uro:FacilityIdAttribute）

uro:FacilityIdAttributeは、施設の位置を特定する情報及び施設を識別する情報を記述するためのデータ型である。 +
uro:FacilityIdAttributeは、施設を識別するための情報として、識別子（uro:id）や正式な名称以外の呼称（uro:alternativeName）に加え、施設の位置を示すための、都道府県（uro:prefecture）、市区町村（uro:city）及び開始位置の経緯度（uro:startLat、uro:startLong）を属性としてもつ。


[[tocH_03_02_03_03]]
====== 施設詳細属性（uro:FacilityAttribute）

uro:FacilityAttributeは、各分野において施設管理に必要となる情報を記述するためのデータ型である。 +
uro:FacilityAttributeは、抽象クラスであり、これを継承する具象となるデータ型に、施設の区分毎に必要となる情報を属性として定義している。

標準製品仕様書では、港湾施設、漁港施設及び公園施設について、細分した施設の区分ごとにデータ型を定義している。また、施設に関する工事や点検の状況や内容を記述するためのデータ型（uro:MaintenanceHistoryAttribute）を定義している。


[[tocH_03_02_04]]
===== ADEで拡張された属性の記述

// 付属書H内に数値地形図属性の記載なしのためリンク張れない。施設管理ならある。

CityGML3.0では、地物型ごとに、属性を拡張するためのデータ型ADEOfXXX（XXXには地物型の名称が入る）が用意されている。また、拡張したデータ型を地物の属性として記述するための主題属性adeOfXXX（XXXには地物型の名称が入る）も用意されている。例えば、建築物（Building）という地物型に属性を追加したい場合、ADEOfBuildingを使う。このデータ型を継承して新しい属性を定義することで、主題属性adeOfBuildingの型として記述できるようになる。

ここで、航路の<<tocH_03_02_01,航路詳細属性>>、<<tocH_03_02_02,データ品質属性>>、数値地形図属性等の主題属性は、上述の仕組みを使って拡張して定義されたデータ型である。これらのデータ型を記述する場合には、拡張した地物型に対応する主題属性adeOfXXX（XXXには地物型の名称が入る）の型として記述しなければならない。

例えば、航路に特化した情報である、<<tocH_03_02_01,航路詳細属性>>はADEOfWaterwayを継承して定義されているため、adeOfWaterwayの型として記述する。また、<<tocH_03_02_02,データ品質属性>>は、ADEOfAbstractCityObjectを継承して定義されているため、adeOfAbstractCityObjectの型として記述する。

このように、ADEで拡張された属性が、どの地物型を拡張して定義されているかによって、主題属性として値を記述する場所が異なることに注意が必要である。

