[[tocD_04]]
=== tran:TrafficArea

tran:TrafficAreaは、車道や歩道のように通行可能な領域（交通領域）の記述に使用する地物型である。

tran:TrafficAreaは、道路の路面を表す地物型である。 +
また、tran:TrafficAreaは、道路上の空間を表す地物型であるtran:TrafficSpaceの境界面（底面）となる。 +
そのため、必ず、TrafficSpaceの部品として記述されなければならない。


[[tocD_04_01]]
==== 交通領域の区分

CityGMLでは、地物型として車道や歩道は用意されておらず、全て、tran:TrafficAreaを用いて記述する。このとき、車道や歩道などの区分は属性tran:functionを用いて行う。

3D都市モデルでは、LODに応じて交通領域を区分するために、LODごとに属性tran:functionの定義域を定めている。この定義域は、<<nilim_kiban_dps,道路基盤地図情報（整備促進版）製品仕様書（案）>>において道路面を構成する地物の区分との整合を考慮している。


[requirement]
.交通領域の区分方法
====
[%metadata]
identifier:: /req/tran/5
subject:: 妥当な交通（道路）データセットの要件
description:: LODに応じた交通領域の区分には、属性tran:functionを用いる。
====

LOD0及びLOD1では、交通領域は全幅道路を基本とする。ただし、ユースケースの必要に応じて<<tab-D-11>>の区分に従い、交通領域を車道部や歩道部等に区分することができる。

LOD2.0では、交通領域は、車道部、車道交差部及び歩道部に区分する（<<tab-D-11>>）。

また、ユースケースの必要に応じて車道部を車線に区分することができる。

[[tab-D-11]]
.LOD0、LOD1及びLOD2.0での交通領域の区分
include::../../../common/sections/codelist_TrafficArea_function_xml_20.adoc[]

車道部（コード1000）は、車道内の車道交差部（コード1020）以外の全ての部分となる。よって、LOD0、LOD1及びLOD2.0では、車道部には、車線だけではなく車線と一体的に舗装されている路肩や非常駐車帯のように、本来は車両の通行の用に供されない場所が含まれる。また、歩道部（コード2000）には、歩道上に設けられた植栽が含まれる。

LOD2.1では、LOD2.1の区分に加え、歩道上の植栽を区分する（<<tab-D-12>>）。歩道部から植栽の範囲が除かれることで、歩道上の通行可能な領域が明らかとなる。

[[tab-D-12]]
.LOD2.1での交通領域の区分
include::../../../common/sections/codelist_TrafficArea_function_xml_21.adoc[]

車道部（コード1000）は、車道内の車線（コード1010）、車道交差部（コード1020）以外の全ての部分となる。

さらに、LOD2.2では、より詳細に道路内を区分できる（<<tab-D-13>>）。この区分は、<<nilim_kiban_dps,道路基盤地図情報（整備促進版）製品仕様書（案）>>において道路面を構成する地物の区分に一致する。どこまで詳細な区分を行うかは、ユースケースに応じて決定してよい。

[[tab-D-13]]
.LOD2.2での交通領域の区分
include::../../../common/sections/codelist_TrafficArea_function_xml_22.adoc[]


車道部（コード1000）は、車道内の通行可能な範囲のうち、車線（コード1010）や車道交差部（コード1020）等、細分された道路の範囲以外の全てとなる。例えば、車両が転回するために設けられた、中央分離帯の切れ目などの部分がこれに該当する。


[[tocD_04_02]]
==== 交通領域の空間属性


[[tocD_04_02_01]]
===== LOD0

tran:TrafficAreaの空間属性は、LOD0において、ネットワークを表す線（core:lod0MultiCurve）とする。


[requirement]
.LOD0 tran:Roadの交差禁止条件
====
[%metadata]
identifier:: /req/tran/6
subject:: 妥当な交通（道路）データセットの要件
description:: LOD0におけるtran:TrafficAreaの空間属性に含まれるgml:LineStringは互いに交差してはならない。
====

これは、一つの交通領域オブジェクトに対して適用するものである。例えば、高架における上の道路と下の道路というように、異なる交通領域オブジェクトの空間属性が交差することを許容する。


[[tocD_04_02_02]]
===== LOD1、LOD2及びLOD3

tran:TrafficAreaの空間属性は、LOD1、LOD2及びLOD3において、多曲面（core:lod1MultiSurface,core:lod2MultiSurface,core:lod3MultiSurface）とする。

道路面は一体的な面であり、その一体的な面を機能により交通領域や交通補助領域に区分している。そのため、道路を構成する交通領域は、他の交通領域や交通補助領域と重なることはない。また、道路を構成する交通領域は、隣接する他の交通領域や交通補助領域と隙間が空いていてはならない。


[requirement]
.tran:TrafficAreaの重なり禁止条件
====
[%metadata]
identifier:: /req/tran/7
subject:: 妥当な交通（道路）データセットの要件
description:: 同一のtran:Roadに含まれるtran:TrafficAreaの空間属性は、他のtran:TrafficAreaやtran:AuxiliaryTrafficAreaの空間属性と重なってはならない。 +
また、同一のtran:Roadに含まれるtran:TrafficAreaの空間属性は、隣接するtran:TrafficAreaやtran:AuxiliaryTrafficAreaの空間属性と、境界線の座標が一致しなければならない。
====

ただし、立体交差を2次元で表現する場合には空間属性が互いに重なってしまう。空間属性の重なりが妥当であるのか否かを判定するために、立体交差では必ず道路のインスタンスを分けなければならない。


[[tocD_04_03]]
==== 交通領域の主題属性


[[tocD_04_03_01]]
===== 機能（tran:function）

tran:functionは、区画線や路面標示、道路標識等により示された交通領域の機能であり、歩道や車道、分離帯のように、道路を横断方向に区分する属性である。

道路基盤地図情報が得られる場合にはこれが利用できる。道路基盤地図情報が得られない場合、LOD3.0までは道路台帳から取得できる。また、LOD3.1以上では航空写真やMMSから取得した画像や点群からの判読が必要となる。


[[tocD_04_03_02]]
===== 表面材質（tran:surfaceMaterial）

tran:surfaceMaterialは、表層舗装の有無及び材質である。同一の交通領域内に複数の表層舗装が混在している場合は、最も面積を占める表層舗装の材質とする。

舗装の材質は、工事完成図書、道路台帳又は現地調査により取得できる。ただし、埋設物管理に伴う掘削や車両乗り入れ口の設置に伴う歩道の切り下げ等の部分的な舗装工事が行われることが多く、最新の状態を把握可能な資料を網羅的に収集することは難しいこと、また、現地調査により最新の状態を把握できるが、広域を対象とする場合にはコストがかかることに注意が必要である。


[[tocD_04_03_03]]
===== 車線数（uro:numberOfLanesInArea）

uro:numberOfLanesInAreaは、交通領域内の車線数である。分離帯により上下が分離されている場合、この属性は当該交通領域（上り又は下り）に含まれる車線の合計数となる。 +
想定される取得方法を以下に示す。

. 都市計画基礎調査で収集されている場合は、これを使用する。
. 道路基盤地図情報より得られる場合は、これを使用する。
. 全国道路・街路交通量情勢調査（一般交通量調査）で収集されている場合は、これを使用する。

既存資料より得られない場合には、航空写真やMMSから取得した画像や点群を用いて判読する。 +
車線数は交通領域が車線に分離されていないLOD2及びLOD3.0において、車線数を把握したい場合に、車道部に対して作成する属性である。

