[[toc7_02]]
=== 配布媒体情報

3D都市モデルに適用する配布媒体情報を以下に示す。ただし、地下埋設物については、<<toc9_08>>の記載を適用する。

[[toc7_02_01]]
==== ファイル単位

[[toc7_02_01_01]]
===== ファイル単位

ファイル単位は、<<tab-7-2>>に示す標準製品仕様書に示す応用スキーマの単位、かつ、JIS X0410において +
定められた地域メッシュの単位を基本とする。一つのファイルには、同一の空間参照系のオブジェクトのみを含む。

地域メッシュは、統合地域メッシュ（第2次地域区画、一辺の長さ約10km）又は基準地域メッシュ（第3次地域区画、一辺の長さ約1km）とする。

[[tab-7-2]]
include::../../../common/sections/com_DataDistribution_FileUnit.adoc[]

[[toc7_02_01_02]]
===== ファイルサイズとファイル分割

1ファイルのデータ量の上限は最大1GBとする。1ファイルのデータ量が1GBを超える場合は、ファイルを分割する。分割したファイルは、同じメッシュを重複して含んではならない。ただし、三次元点群データをインライン記述したファイルは、ファイル分割を禁止する。点群をインライン記述する場合は、そのファイルサイズを1GB以内に収めること。

[[tab-7-3]]
include::../../../common/sections/com_DataDistribution_FileDivisionRules.adoc[]


[[toc7_02_02]]
==== 境界線上の地物の取り扱い

[[toc7_02_02_01]]
===== 地域メッシュの境界線上に存在する地物

ファイル単位となる地域メッシュのメッシュの境界線上に存在する地物は分割しない。複数のメッシュに跨って存在する地物は、それぞれのメッシュに平面投影した形状が含まれる面積の割合を算出し、この割合が最も大きいメッシュに対応するファイルに含む。面積は、小数点2桁（3桁目で四捨五入、単位はm2）で比較する。面積が同じ場合はメッシュ番号の小さい方とする。

[[toc7_02_02_02]]
===== 行政区域の境界線上に存在する地物

データセットの単位となる行政区域の境界線に跨って存在する地物（例：橋梁、トンネル及びその他の構造物）は分割しない。複数の行政区域に跨って存在する地物は、それぞれの都市のデータセットに含めることを許容する。

[[toc7_02_03]]
==== ファイル名称

ファイル名称（拡張子を除いた部分）は、``[メッシュコード]\_[地物型]_[CRS]_[オプション]``とする。
// ファイル名称（拡張子を除いた部分）は、``[メッシュコード]_[地物型]_[CRS]_[オプション]``とする。

[[tab-7-4]]
include::../../../common/sections/com_DataDistribution_FileComposition.adoc[]

[[toc7_02_03_01]]
===== [メッシュコード]

``[メッシュコード]``は、ファイルの単位に対応する地域メッシュのコードとする。ファイルを分割した場合は、最も若い（左下）のメッシュコードを付与する。

[[toc7_02_03_02]]
===== [地物型]

``[地物型]``にはファイルに含まれる応用スキーマを識別する接頭辞（<<tab-7-5>>）を付与する。

[[tab-7-5]]
include::../../../common/sections/com_DataDistribution_Prefix.adoc[]

[[toc7_02_03_03]]
===== [CRS]

``[CRS]``には、当該ファイルに含まれるオブジェクトの空間参照系の略称（半角数字）としてEPSGコード（ https://epsg.org/home.html[https://epsg.org/home.html] ）を入力する。
EPSGコードは、空間参照系に与えられた固有の識別子である。標準製品仕様書で使用する空間参照系の略称を下表に示す。

[[tab-7-6]]
[cols="4a,1a"]
.空間参照系の略称
|===
| オブジェクトに適用される空間参照系 | 略称

| 日本測地系2011における経緯度座標系と東京湾平均海面を基準とする標高の複合座標参照系 | 6697

|===

なお、標準製品仕様書第2.3版までは、高さとして標高を含むファイルと、仮想的な高さを含むファイルを識別するために、空間参照系の略称として2次元の座標参照系を示す「6668」も採用していた。

しかし、標準製品仕様書第3.0版において、応用スキーマごとにLODの定義を明確にしたこと、また、対象とするLODにLOD0も含めた。これにより、高さとして標高を含むファイルと仮想的な高さを含むファイルを識別子で区分することが不要となったため、略称として6668は削除した。

3D都市モデルの各ファイルに適用する空間参照系の略称は、「6697」に統一する。

[[toc7_02_03_04]]
===== [オプション]

``[オプション]``は、メッシュ単位及び地物型単位となるファイルをさらに分割したい場合に使用する。使用しない場合は区切り文字と共に省略する。<<tab-7-7>>に標準製品仕様書において定めるオプションに使用可能な文字列を示す。

[[tab-7-7]]
include::../../../common/sections/com_DataDistribution_Option.adoc[]

このうち、``[識別子]``は、拡張製品仕様書において定めることのできる任意の文字列である。``[識別子]``を使用する場合は、``[識別子]``を含むオプションの文字列、適用するフォルダ名及びオプションの文字列の意味の一覧（<<tab-7-8>>）を作成する。なお、``[識別子]``を含むオプションの文字列は、オプションに使用するほかの文字列と重複してはならない。

[[tab-7-8]]
[cols="1a,2a,4a"]
.拡張製品仕様書で追加するオプションの文字列
|===
| オプション | 適用するフォルダ名 | 文字列の意味

| 　 | 　 | 　
| 　 | 　 | 　
| 　 | 　 | 　
| 　 | 　 | 　

|===

[[toc7_02_04]]
==== フォルダ構成とフォルダ名称

[[toc7_02_04_01]]
===== フォルダ構成

データ製品のフォルダ構成を示す。

[[tab-7-9]]
include::../../../common/sections/com_DataDistribution_FolderStructure.adoc[]

[[toc7_02_04_02]]
===== ルートフォルダの命名規則

ルートフォルダの名称は、``[都市コード]\_[都市名英名]_[提供者区分]\_[整備年度]_citygml_[更新回数]_[オプション]``とする。
// ルートフォルダの名称は、``[都市コード]_[都市名英名]_[提供者区分]_[整備年度]_citygml_[更新回数]_[オプション]``とする。

[[tab-7-10]]
[cols="1a,4a,2a"]
.ルートフォルダの命名規則
|===
| ルートフォルダ名称の構成要素 | 説明 | 使用可能な文字

| ``[都市コード]`` 
| 3D都市モデルを作成する範囲を識別するコード。 +
作成範囲が市区町村の場合は、都道府県コード（2桁）と市区町村コード（3桁）の組み合わせからなる5桁の数字とする。 +
都道府県の場合は、都道府県コード（2桁）とする。
|半角数字

| ``[都市名英名]`` 
| 市区町村コードに対応する都道府県名又は市区町村名の英名。 +
英名の表記は、デジタル庁が定める「行政基本情報データ連携モデル_住所」に従う。
|半角英字

| ``[提供者区分]``
|データセットの提供者を識別するための文字列。 +
提供者が市区町村又は都道府県の場合は、以下とする。 +
city ：市区町村 +
pref ：都道府県 +
提供者が市区町村及び都道府県以外の場合は、``[事業分野]``-``[提供者]``の組み合わせとする。 +
``[事業分野]``は、提供者の事業分野の略称であり、半角英数字の組み合わせとする。 +
``[提供者]``は、当該提供者を識別する任意の文字列であり、半角英数字とする。 +
　 +
標準製品仕様書で使用する事業分野の略称 +
unf: ユーティリティ事業 +
 道路事業 +
rwy: 鉄道事業 +
　 +
``[提供者区分]``の例を以下に示す。ただし、``[提供者]``の部分はいずれも作成例である。 +
tran-mlit：国土交通省が提供する交通（道路）モデル +
unf-tg：東京ガスが提供する地下埋設物モデル +
tran-enexco：NEXCO東日本が整備する交通（道路）モデル +
rwy-jre：JR東日本が提供する交通（鉄道）モデル
| 半角英数字、区切り文字（-）

| ``[整備年度]`` 
| 3D都市モデルを整備した年度（半角数字4桁の西暦）とする。 +
整備とは、以下の1（新規整備）に加え、2及び3を含む。 +
1. データセットの追加（新規整備） +
2. 地物型の追加 +
3. 地物の追加（整備範囲の拡張、既存地物の更新） +
以下の4から6は含まない。 +
4. 空間属性の追加 +
5. 主題属性の追加 +
6. 標準製品仕様書の改定に伴うバージョンアップ
|半角数字

| ``[更新回数]`` 
| 履歴管理用に半角数字を付す。初回に作成した成果物は1とする。以降、修正等を行った場合はバージョンアップごとに数字を加算していく。 +
``[更新回数]``は``[整備年度]``ごとに加算する。``[整備年度]``が変わった場合は、1から開始する。
|半角数字

| ``[オプション]`` 
| 成果品が複数種類作成される場合に、これらを識別する任意の文字列とする。半角英数字のみ使用可とする。成果品が1種類の場合は、``_[オプション]``は省略する。
|半角英数字、区切り文字（-）

| _ 
| ルートフォルダ名称の構成要素同士の区切り文字 
| ルートフォルダル名称の構成要素同士を区切る場合には、アンダースコア（_）のみを用いる。

|===

[[toc7_02_04_03]]
===== サブフォルダの作成

3D都市モデルを格納するudxフォルダには、3D都市モデルの応用スキーマに対応するサブフォルダを作成し、各データ製品を格納する。

災害リスクモデルについては、災害の種類ごとに分けてサブフォルダ（fld、tnm、htd、ifld、rfld及びlsld）を作成する。また、災害リスクのうち、浸水想定区域のサブフォルダ（fld、tnm、htd、ifld及びrfld）には、さらに区域図ごとのサブフォルダを設ける。サブフォルダを作成する場合は、下表に従い、作成したサブフォルダの一覧を付す。

拡張製品仕様書において災害リスク（浸水）モデルを作成する場合は、以下に示す表を用いて、対応する災害リスク（浸水）モデルのフォルダ構成を示すこと。

* 洪水浸水想定区域のフォルダ構成
+
サブフォルダ「fld」の中に、国を示すサブフォルダ「natl」と都道府県を示すサブフォルダ「pref」を作成し、「natl」及び「pref」の中にさらに洪水浸水想定区域図ごとのサブフォルダを作成する。 +
なお、「natl」と「pref」には、水防法第14条第1項に定める「洪水浸水想定区域」である災害リスク（浸水）モデルを格納する。また、水防法第14条第1項に定める「洪水浸水想定区域」以外の洪水ハザードマップ等に基づく浸水面や、破堤点ごと、時間経過ごとの浸水面を表現する災害リスク（浸水）モデルは、サブフォルダ「org」を作成し、この中にさらに区域図ごとのサブフォルダを作成する。 +
サブフォルダを作成する場合は、拡張製品仕様書において、下表を用いてサブフォルダ名及びフォルダの説明を示す。

[[tab-7-11]]
[cols="1a,2a,4a"]
.洪水浸水想定区域のフォルダ構成
|===
| フォルダ名 | サブフォルダ名 | フォルダの説明（洪水浸水想定区域図の名称）

| natl | 　 | 　
| pref | 　 | 　
| org | 　 | 　

|===

* 津波浸水想定のフォルダ構成
+
サブフォルダ「tnm」の中に、津波浸水想定ごとのサブフォルダを作成する。 +
サブフォルダを作成する場合は、拡張製品仕様書において、下表を用いてサブフォルダ名及びフォルダの説明を示す。

[[tab-7-12]]
[cols="1a,3a"]
.津波浸水想定のフォルダ構成
|===
| サブフォルダ名 | フォルダの説明（津波浸水想定の名称）

| 　 | 　
| 　 | 　

|===

* 高潮浸水想定区域のフォルダ構成
+
サブフォルダ「htd」の中に、高潮浸水想定区域図ごとのサブフォルダを作成する。 +
サブフォルダを作成する場合は、拡張製品仕様書において、下表を用いてサブフォルダ名及びフォルダの説明を示す。

[[tab-7-13]]
[cols="1a,3a"]
.高潮浸水想定区域のフォルダ構成
|===
| サブフォルダ名 | フォルダの説明（高潮浸水想定区域図の名称）

| 　 | 　
| 　 | 　

|===

* 内水浸水想定区域のフォルダ構成
+
サブフォルダ「ifld」の中に、内水浸水想定区域図ごとのサブフォルダを作成する。 +
サブフォルダを作成する場合は、拡張製品仕様書において、下表を用いてサブフォルダ名及びフォルダの説明を示す。

[[tab-7-14]]
[cols="1a,3a"]
.内水浸水想定区域図のフォルダ構成
|===
| サブフォルダ名 | フォルダの説明（内水浸水想定区域図の名称）

| 　 | 　
| 　 | 　

|===

* ため池ハザードマップのフォルダ構成
+
サブフォルダ「rfld」の中に、ため池ハザードマップごとのサブフォルダを作成する。 +
サブフォルダを作成する場合は、拡張製品仕様書において、下表を用いてサブフォルダ名及びフォルダの説明を示す。

[[tab-7-15]]
[cols="1a,3a"]
.ため池ハザードマップのフォルダ構成
|===
| サブフォルダ名 | フォルダの説明（ため池ハザードマップの名称）

| 　 | 　
| 　 | 　

|===

[[toc7_02_05]]
==== 成果品の単位と空間範囲

成果品の単位は基礎自治体とし、成果品の空間範囲は基礎自治体が整備する原典資料の整備範囲と一致させることを基本とする。

* ただし、都道府県等広域で原典資料が整備されている場合の市区町村の空間範囲は、地物型のファイル単位（<<toc7_02_01>>）に応じて、市区町村の行政区域を包含する基準地域メッシュ（第3次地域区画）又は統合地域メッシュ（第2次地域区画）とする。

* <<fig-7-1>>は都道府県で都市計画基本図が整備されている場合の例である。A市とB市にはそれぞれの空間範囲を包含するメッシュに該当するファイルがそれぞれのデータセットに含まれる。このとき、A市とB市の行政界を跨ぐメッシュのファイルは、それぞれのデータセットに重複して含まれる。

[[fig-7-1]]
.都道府県で都市計画基本図が整備されている場合に重複して格納されるファイルの例
image::../../sources/images/001_sec07_001.svg[]

[[toc7_02_06]]
==== 媒体名

DVD、HDD又はウェブサイトからのダウンロードとする。

ルートフォルダをZIP形式（拡張子.zip）又は7Z形式（拡張子.7z）に圧縮する。圧縮後のファイル名称は、以下とする。

``[都市コード]\_[都市名英名]_[提供者区分]\_[整備年度]_citygml_[更新回数]_[オプション]``
// ``[都市コード]_[都市名英名]_[提供者区分]_[整備年度]_citygml_[更新回数]_[オプション]``

（オープンデータの場合は、``[都市コード]\_[都市名英名]_[提供者区分]\_[整備年度]_citygml_[更新回数]_[オプション]_op``）
// （オープンデータの場合は、``[都市コード]_[都市名英名]_[提供者区分]_[整備年度]_citygml_[更新回数]_[オプション]_op``）

``[都市コード]``、``[都市名英名]``、``[提供者区分]``、``[整備年度]``及び``[更新回数]``の表記は、「<<toc7_02_04>>」に示すルートフォルダの命名規則に従う。 +
``[オプション]``は、成果品が複数種類作成される場合に、これらを識別するために使用する、半角英数字からなる任意の文字列とする。成果品が1種類の場合は、``_[オプション]``を省略する。

圧縮後のファイルサイズが160GBを越え、ファイルを分割した場合には、分割後のファイル名称及び各ファイルに格納したフォルダ又はファイルを一覧で示す。

[[tab-7-16]]
[cols="1a,3a"]
.分割したファイルの概要
|===
| 分割後ファイル名称 | 格納したフォルダ又はファイルの種類

| 　 | 　
| 　 | 　

|===

[[toc7_02_07]]
==== オープンデータのための配布媒体情報

作成したデータ製品から、オープンデータを作成する場合には、以下に従う。

* 「ファイル単位」は「<<toc7_02_01>>」に従う。

* 「境界線上の地物の取り扱い」は、「<<toc7_02_02>>」に従う。

* 3D都市モデルの「ファイル命名規則」は``[メッシュコード]\_[地物型]_[CRS]_[オプション]_op``とする。``[メッシュコード]``、``[地物型]``、``[CRS]``及び``[オプション]``の表記は「<<toc7_02_03>>」に従う。また、オープンデータであることを明らかにするため、末尾に「_op」を付与する。
// * 3D都市モデルの「ファイル命名規則」は``[メッシュコード]_[地物型]_[CRS]_[オプション]_op``とする。``[メッシュコード]``、``[地物型]``、``[CRS]``及び``[オプション]``の表記は「<<toc7_02_03>>」に従う。また、オープンデータであることを明らかにするため、末尾に「_op」を付与する。

* ファイル構成は「<<toc7_02_04>>」に従う。ただし、ルートフォルダの名称の末尾に「_op」を付与する。

* 媒体名は「<<toc7_02_06>>」に従う。
