name: test-2026-work

on:
  push:
    branches: [ 2026-plateau-work ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Swap Space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10 # Adds 10GB of virtual memory

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Generate Metanorma collection
        env:
          JAVA_OPTS: "-Xmx6g"
          NODE_OPTIONS: "--max-old-space-size=6144"
        # run: bundle exec metanorma collection collection.yml --agree-to-terms
        run: bundle exec metanorma sources/001-cg3pre/document.adoc --agree-to-terms

      - name: Upload collection artifacts
        uses: actions/upload-artifact@v4
        with:
          name: collection
          # path: |
          #   index.html
          #   *_index.html
          #   document*.html
          #   collection.presentation.xml
          #   sources/001-cg3pre/cover.html
          #   sources/001-cg3pre/index.html
          path: |
            sources/001-cg3pre/document.err.html
            sources/001-cg3pre/document.html
            sources/001-cg3pre/document.pdf
            sources/001-cg3pre/document.pdf.err
            sources/001-cg3pre/document.presentation.xml
            sources/001-cg3pre/document.rxl
            sources/001-cg3pre/document.xml
