[[tocT_03]]
=== wtr:WaterBody

wtr:WaterBodyは、河川や湖沼などの水部の記述に使用する地物型である。


[[tocT_03_01]]
==== 水部の空間属性

wtr:WaterBodyの空間属性には、LOD0からLOD3までの4つがある。 +
ただし、LOD1において空間属性は空となる。


[[tocT_03_01_01]]
===== LOD0

wtr:WaterBodyの空間属性は、LOD0において、線（core:lod0MultiCurve）として記述する。 +
このとき水部オブジェクトは、水部モデル（LOD0）の定義に従ったものでなければならない。


[requirement]
.水部のLOD0形状定義
====
[%metadata]
identifier:: /req/wtr/2
subject:: 妥当な水部データセットの要件
description:: 水部のLOD0の形状は、水部モデル（LOD0）の定義に従う。
====


[[tocT_03_01_02]]
===== LOD1

wtr:WaterBodyの空間属性は、LOD1において、空となる。 +
ただし、この部品となる地物であるwtr:WaterSurface（水面）が多曲面（core:lod1MultiSurface）をもつ。 +
このとき水部オブジェクトは、水部モデル（LOD1）の定義に従ったものでなければならない。


[requirement]
.水部のLOD1形状定義
====
[%metadata]
identifier:: /req/wtr/3
subject:: 妥当な水部データセットの要件
description:: 水部のLOD1の形状は水部モデル（LOD1）の定義に従う。
====


[[tocT_03_01_03]]
===== LOD2

wtr:WaterBodyの空間属性は、LOD2において、立体（core:lod2Solid）となる。 +
wtr:WaterBodyの立体は、水涯線により囲まれた面（水面）、水底面及び管理区間や行政区域を区切る面を境界面とする。 +
このとき、水部オブジェクトは、水部モデル（LOD2）の定義に従ったものでなければならない。


[requirement]
.水部のLOD2形状定義
====
[%metadata]
identifier:: /req/wtr/4
subject:: 妥当な水部データセットの要件
description:: 水部のLOD2の形状は、水部モデル（LOD2）の定義に従う。
====

LOD2.0の場合、wtr:WaterBodyの立体は水中に存在する橋脚等の構造物の空間を含めた立体となる。 +
LOD2.1の場合、wtr:WaterBodyの立体は水中に存在する橋脚等の構造物の空間を除いた立体となる。


[[tocT_03_01_04]]
===== LOD3

wtr:WaterBodyの空間属性は、LOD3において、立体（core:lod3Solid）となる。 +
wtr:WaterBodyの立体は、水涯線により囲まれた面（水面）、水底面及び管理区間や行政区域を区切る面を境界面とする。 +
このとき、水部オブジェクトは、水部モデル（LOD3）の定義に従ったものでなければならない。


[requirement]
.水部のLOD3形状定義
====
[%metadata]
identifier:: /req/wtr/5
subject:: 妥当な水部データセットの要件
description:: 水部のLOD3の形状は、水部モデル（LOD3）の定義に従う。
====

LOD3.0の場合、wtr:WaterBodyの立体は水中に存在する橋脚等の構造物の空間を含めた立体となる。 +
LOD3.1の場合、wtr:WaterBodyの立体は水中に存在する橋脚等の構造物の空間を除いた立体となる。


[[tocT_03_02]]
==== 水部の主題属性


[[tocT_03_02_01]]
===== データ品質属性（urc:DataQualityAttribute）

水部オブジェクトの作成に使用した原典資料の記録や、適用した詳細なLODの区分を示すための属性である。 +
使用した原典資料やそれに基づくデータの品質、また、採用したLODは、データセットのメタデータに記録できる。ただし、データセット全体に対して一つのメタデータを作成することが基本となり、個々の都市オブジェクトの品質を記録することは困難である。

同じデータセットの中に、航空写真測量により作成したその他の構造物オブジェクトや完成図等から作成したその他の構造物オブジェクトというように、複数の品質をもつ都市オブジェクトが混在している場合には、都市オブジェクトごとにこのデータ品質属性を使用して、品質情報を記録することで、その品質を明確にできる。

そこで、標準製品仕様書では、個々のデータに対してデータ品質に関する情報を記述するための属性として、「データ品質属性」（urc:DataQualityAttribute）を定義している。データ品質属性は、属性としてデータ作成に使用した原典資料の地図情報レベル、その他原典資料の諸元及び精緻化したLODをもつ。

3D都市モデルに含まれる全ての水部モデルは、このデータ品質属性を必ず作成しなければならない。ただし、水部（wtr:WaterBody）に対してデータ品質属性を付与することはできるが、これを構成する水面等の境界面（wtr:AbstractBoundarySurfaceの下位クラス）にデータ品質属性を付与することはできない。


[[tocT_03_02_02]]
===== ADEで拡張された属性の記述

CityGML3.0では、地物型ごとに、属性を拡張するためのデータ型ADEOfXXX（XXXには地物型の名称が入る）が用意されている。また、拡張したデータ型を地物の属性として記述するための主題属性adeOfXXX（XXXには地物型の名称が入る）も用意されている。例えば、建築物（Building）という地物型に属性を追加したい場合、ADEOfBuildingを使う。このデータ型を継承して新しい属性を定義することで、主題属性adeOfBuildingの型として記述できるようになる。

ここで、水部の<<tocT_03_02_01,データ品質属性>>は、上述の仕組みを使って拡張して定義されたデータ型である。これらのデータ型を記述する場合には、拡張した地物型に対応する主題属性adeOfXXX（XXXには地物型の名称が入る）の型として記述しなければならない。

例えば、<<tocT_03_02_01,データ品質属性>>はADEOfAbstractCityObjectを継承して定義されているため、adeOfAbstractCityObjectの型として記述する。

このように、ADEで拡張された属性が、どの地物型を拡張して定義されているかによって、主題属性として値を記述する場所が異なることに注意が必要である。

